// Industry and Job data for Geographic Arbitrage Calculator

export interface Job {
  id: string;
  title: string;
  ukAverageSalary: number;
  remoteability: 'fully_remote' | 'hybrid' | 'on_site';
  demandTrend: 'high_growth' | 'growing' | 'stable' | 'declining';
  visaSponsorship: 'common' | 'possible' | 'rare';
  freelanceViable: boolean;
  description: string;
}

export interface Industry {
  id: string;
  name: string;
  icon: string;
  description: string;
  jobs: Job[];
}

export const INDUSTRIES: Industry[] = [
  {
    id: 'technology',
    name: 'Technology',
    icon: '💻',
    description: 'Software, IT, and digital technology roles',
    jobs: [
      {
        id: 'software_engineer',
        title: 'Software Engineer',
        ukAverageSalary: 55000,
        remoteability: 'fully_remote',
        demandTrend: 'high_growth',
        visaSponsorship: 'common',
        freelanceViable: true,
        description: 'Build and maintain software applications',
      },
      {
        id: 'frontend_developer',
        title: 'Frontend Developer',
        ukAverageSalary: 48000,
        remoteability: 'fully_remote',
        demandTrend: 'growing',
        visaSponsorship: 'common',
        freelanceViable: true,
        description: 'Create user interfaces with React, Vue, Angular',
      },
      {
        id: 'backend_developer',
        title: 'Backend Developer',
        ukAverageSalary: 52000,
        remoteability: 'fully_remote',
        demandTrend: 'growing',
        visaSponsorship: 'common',
        freelanceViable: true,
        description: 'Server-side development and APIs',
      },
      {
        id: 'fullstack_developer',
        title: 'Full Stack Developer',
        ukAverageSalary: 55000,
        remoteability: 'fully_remote',
        demandTrend: 'high_growth',
        visaSponsorship: 'common',
        freelanceViable: true,
        description: 'End-to-end web application development',
      },
      {
        id: 'mobile_developer',
        title: 'Mobile Developer',
        ukAverageSalary: 52000,
        remoteability: 'fully_remote',
        demandTrend: 'growing',
        visaSponsorship: 'common',
        freelanceViable: true,
        description: 'iOS and Android app development',
      },
      {
        id: 'devops_engineer',
        title: 'DevOps Engineer',
        ukAverageSalary: 60000,
        remoteability: 'fully_remote',
        demandTrend: 'high_growth',
        visaSponsorship: 'common',
        freelanceViable: true,
        description: 'CI/CD, cloud infrastructure, automation',
      },
      {
        id: 'data_engineer',
        title: 'Data Engineer',
        ukAverageSalary: 58000,
        remoteability: 'fully_remote',
        demandTrend: 'high_growth',
        visaSponsorship: 'common',
        freelanceViable: true,
        description: 'Build data pipelines and infrastructure',
      },
      {
        id: 'data_scientist',
        title: 'Data Scientist',
        ukAverageSalary: 62000,
        remoteability: 'fully_remote',
        demandTrend: 'high_growth',
        visaSponsorship: 'common',
        freelanceViable: true,
        description: 'Machine learning and statistical analysis',
      },
      {
        id: 'ml_engineer',
        title: 'ML/AI Engineer',
        ukAverageSalary: 70000,
        remoteability: 'fully_remote',
        demandTrend: 'high_growth',
        visaSponsorship: 'common',
        freelanceViable: true,
        description: 'Build and deploy machine learning models',
      },
      {
        id: 'qa_engineer',
        title: 'QA Engineer',
        ukAverageSalary: 42000,
        remoteability: 'fully_remote',
        demandTrend: 'stable',
        visaSponsorship: 'possible',
        freelanceViable: true,
        description: 'Software testing and quality assurance',
      },
      {
        id: 'security_engineer',
        title: 'Security Engineer',
        ukAverageSalary: 65000,
        remoteability: 'hybrid',
        demandTrend: 'high_growth',
        visaSponsorship: 'common',
        freelanceViable: true,
        description: 'Cybersecurity and penetration testing',
      },
      {
        id: 'solutions_architect',
        title: 'Solutions Architect',
        ukAverageSalary: 80000,
        remoteability: 'hybrid',
        demandTrend: 'growing',
        visaSponsorship: 'common',
        freelanceViable: true,
        description: 'Design complex technical solutions',
      },
      {
        id: 'it_support',
        title: 'IT Support Specialist',
        ukAverageSalary: 32000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'possible',
        freelanceViable: false,
        description: 'Technical support and helpdesk',
      },
      {
        id: 'network_engineer',
        title: 'Network Engineer',
        ukAverageSalary: 48000,
        remoteability: 'on_site',
        demandTrend: 'stable',
        visaSponsorship: 'possible',
        freelanceViable: false,
        description: 'Network infrastructure management',
      },
    ],
  },
  {
    id: 'product_design',
    name: 'Product & Design',
    icon: '🎨',
    description: 'Product management, UX/UI, and creative design',
    jobs: [
      {
        id: 'product_manager',
        title: 'Product Manager',
        ukAverageSalary: 65000,
        remoteability: 'fully_remote',
        demandTrend: 'high_growth',
        visaSponsorship: 'common',
        freelanceViable: true,
        description: 'Define product strategy and roadmap',
      },
      {
        id: 'product_owner',
        title: 'Product Owner',
        ukAverageSalary: 55000,
        remoteability: 'fully_remote',
        demandTrend: 'growing',
        visaSponsorship: 'possible',
        freelanceViable: true,
        description: 'Agile product ownership and backlog management',
      },
      {
        id: 'ux_designer',
        title: 'UX Designer',
        ukAverageSalary: 48000,
        remoteability: 'fully_remote',
        demandTrend: 'growing',
        visaSponsorship: 'common',
        freelanceViable: true,
        description: 'User experience research and design',
      },
      {
        id: 'ui_designer',
        title: 'UI Designer',
        ukAverageSalary: 45000,
        remoteability: 'fully_remote',
        demandTrend: 'growing',
        visaSponsorship: 'possible',
        freelanceViable: true,
        description: 'Visual interface design',
      },
      {
        id: 'product_designer',
        title: 'Product Designer',
        ukAverageSalary: 52000,
        remoteability: 'fully_remote',
        demandTrend: 'high_growth',
        visaSponsorship: 'common',
        freelanceViable: true,
        description: 'End-to-end product design',
      },
      {
        id: 'graphic_designer',
        title: 'Graphic Designer',
        ukAverageSalary: 35000,
        remoteability: 'fully_remote',
        demandTrend: 'stable',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Visual design and branding',
      },
      {
        id: 'motion_designer',
        title: 'Motion Designer',
        ukAverageSalary: 42000,
        remoteability: 'fully_remote',
        demandTrend: 'growing',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Animation and motion graphics',
      },
      {
        id: 'ux_researcher',
        title: 'UX Researcher',
        ukAverageSalary: 50000,
        remoteability: 'hybrid',
        demandTrend: 'growing',
        visaSponsorship: 'possible',
        freelanceViable: true,
        description: 'User research and usability testing',
      },
    ],
  },
  {
    id: 'marketing',
    name: 'Marketing & Growth',
    icon: '📈',
    description: 'Digital marketing, content, and growth roles',
    jobs: [
      {
        id: 'marketing_manager',
        title: 'Marketing Manager',
        ukAverageSalary: 50000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'possible',
        freelanceViable: true,
        description: 'Lead marketing strategy and campaigns',
      },
      {
        id: 'digital_marketing',
        title: 'Digital Marketing Specialist',
        ukAverageSalary: 38000,
        remoteability: 'fully_remote',
        demandTrend: 'growing',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Online marketing and advertising',
      },
      {
        id: 'seo_specialist',
        title: 'SEO Specialist',
        ukAverageSalary: 40000,
        remoteability: 'fully_remote',
        demandTrend: 'growing',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Search engine optimization',
      },
      {
        id: 'content_marketer',
        title: 'Content Marketing Manager',
        ukAverageSalary: 45000,
        remoteability: 'fully_remote',
        demandTrend: 'growing',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Content strategy and production',
      },
      {
        id: 'social_media_manager',
        title: 'Social Media Manager',
        ukAverageSalary: 35000,
        remoteability: 'fully_remote',
        demandTrend: 'stable',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Social media strategy and management',
      },
      {
        id: 'growth_manager',
        title: 'Growth Manager',
        ukAverageSalary: 55000,
        remoteability: 'fully_remote',
        demandTrend: 'high_growth',
        visaSponsorship: 'possible',
        freelanceViable: true,
        description: 'Data-driven growth strategies',
      },
      {
        id: 'ppc_specialist',
        title: 'PPC/Paid Ads Specialist',
        ukAverageSalary: 42000,
        remoteability: 'fully_remote',
        demandTrend: 'growing',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Paid advertising campaigns',
      },
      {
        id: 'email_marketer',
        title: 'Email Marketing Specialist',
        ukAverageSalary: 38000,
        remoteability: 'fully_remote',
        demandTrend: 'stable',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Email campaigns and automation',
      },
      {
        id: 'brand_manager',
        title: 'Brand Manager',
        ukAverageSalary: 52000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'possible',
        freelanceViable: true,
        description: 'Brand strategy and identity',
      },
    ],
  },
  {
    id: 'content_media',
    name: 'Content & Media',
    icon: '✍️',
    description: 'Writing, editing, video, and multimedia',
    jobs: [
      {
        id: 'content_writer',
        title: 'Content Writer',
        ukAverageSalary: 32000,
        remoteability: 'fully_remote',
        demandTrend: 'stable',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Articles, blogs, and web content',
      },
      {
        id: 'copywriter',
        title: 'Copywriter',
        ukAverageSalary: 38000,
        remoteability: 'fully_remote',
        demandTrend: 'stable',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Advertising and marketing copy',
      },
      {
        id: 'technical_writer',
        title: 'Technical Writer',
        ukAverageSalary: 45000,
        remoteability: 'fully_remote',
        demandTrend: 'growing',
        visaSponsorship: 'possible',
        freelanceViable: true,
        description: 'Documentation and technical content',
      },
      {
        id: 'editor',
        title: 'Editor',
        ukAverageSalary: 35000,
        remoteability: 'fully_remote',
        demandTrend: 'stable',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Content editing and proofreading',
      },
      {
        id: 'video_producer',
        title: 'Video Producer',
        ukAverageSalary: 40000,
        remoteability: 'hybrid',
        demandTrend: 'growing',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Video content production',
      },
      {
        id: 'video_editor',
        title: 'Video Editor',
        ukAverageSalary: 35000,
        remoteability: 'fully_remote',
        demandTrend: 'growing',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Video editing and post-production',
      },
      {
        id: 'podcast_producer',
        title: 'Podcast Producer',
        ukAverageSalary: 38000,
        remoteability: 'fully_remote',
        demandTrend: 'growing',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Podcast production and editing',
      },
      {
        id: 'journalist',
        title: 'Journalist',
        ukAverageSalary: 32000,
        remoteability: 'hybrid',
        demandTrend: 'declining',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'News reporting and investigation',
      },
    ],
  },
  {
    id: 'finance',
    name: 'Finance & Accounting',
    icon: '💰',
    description: 'Financial services, accounting, and analysis',
    jobs: [
      {
        id: 'accountant',
        title: 'Accountant',
        ukAverageSalary: 42000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'possible',
        freelanceViable: true,
        description: 'Financial accounting and reporting',
      },
      {
        id: 'financial_analyst',
        title: 'Financial Analyst',
        ukAverageSalary: 50000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'possible',
        freelanceViable: true,
        description: 'Financial modeling and analysis',
      },
      {
        id: 'management_accountant',
        title: 'Management Accountant',
        ukAverageSalary: 48000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'possible',
        freelanceViable: true,
        description: 'Budgeting and management reporting',
      },
      {
        id: 'auditor',
        title: 'Auditor',
        ukAverageSalary: 45000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'possible',
        freelanceViable: true,
        description: 'Internal and external auditing',
      },
      {
        id: 'tax_advisor',
        title: 'Tax Advisor',
        ukAverageSalary: 52000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'possible',
        freelanceViable: true,
        description: 'Tax planning and compliance',
      },
      {
        id: 'investment_analyst',
        title: 'Investment Analyst',
        ukAverageSalary: 60000,
        remoteability: 'on_site',
        demandTrend: 'stable',
        visaSponsorship: 'common',
        freelanceViable: false,
        description: 'Investment research and recommendations',
      },
      {
        id: 'financial_controller',
        title: 'Financial Controller',
        ukAverageSalary: 75000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'possible',
        freelanceViable: false,
        description: 'Financial operations management',
      },
      {
        id: 'bookkeeper',
        title: 'Bookkeeper',
        ukAverageSalary: 28000,
        remoteability: 'fully_remote',
        demandTrend: 'stable',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Day-to-day financial records',
      },
      {
        id: 'payroll_specialist',
        title: 'Payroll Specialist',
        ukAverageSalary: 32000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Payroll processing and compliance',
      },
    ],
  },
  {
    id: 'sales_business',
    name: 'Sales & Business Development',
    icon: '🤝',
    description: 'Sales, partnerships, and business growth',
    jobs: [
      {
        id: 'sales_manager',
        title: 'Sales Manager',
        ukAverageSalary: 55000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'possible',
        freelanceViable: false,
        description: 'Lead sales teams and strategy',
      },
      {
        id: 'account_executive',
        title: 'Account Executive',
        ukAverageSalary: 45000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'possible',
        freelanceViable: false,
        description: 'B2B sales and client relationships',
      },
      {
        id: 'sdr',
        title: 'Sales Development Rep (SDR)',
        ukAverageSalary: 32000,
        remoteability: 'fully_remote',
        demandTrend: 'growing',
        visaSponsorship: 'rare',
        freelanceViable: false,
        description: 'Lead generation and outreach',
      },
      {
        id: 'business_development',
        title: 'Business Development Manager',
        ukAverageSalary: 55000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'possible',
        freelanceViable: true,
        description: 'Partnerships and growth opportunities',
      },
      {
        id: 'customer_success',
        title: 'Customer Success Manager',
        ukAverageSalary: 45000,
        remoteability: 'fully_remote',
        demandTrend: 'high_growth',
        visaSponsorship: 'possible',
        freelanceViable: false,
        description: 'Client retention and satisfaction',
      },
      {
        id: 'account_manager',
        title: 'Account Manager',
        ukAverageSalary: 42000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'possible',
        freelanceViable: false,
        description: 'Client relationship management',
      },
    ],
  },
  {
    id: 'hr_people',
    name: 'HR & People Operations',
    icon: '👥',
    description: 'Human resources, recruiting, and people management',
    jobs: [
      {
        id: 'hr_manager',
        title: 'HR Manager',
        ukAverageSalary: 50000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'possible',
        freelanceViable: true,
        description: 'HR strategy and operations',
      },
      {
        id: 'recruiter',
        title: 'Recruiter',
        ukAverageSalary: 38000,
        remoteability: 'fully_remote',
        demandTrend: 'stable',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Talent acquisition and hiring',
      },
      {
        id: 'tech_recruiter',
        title: 'Technical Recruiter',
        ukAverageSalary: 45000,
        remoteability: 'fully_remote',
        demandTrend: 'growing',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Tech talent acquisition',
      },
      {
        id: 'hr_business_partner',
        title: 'HR Business Partner',
        ukAverageSalary: 55000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'possible',
        freelanceViable: false,
        description: 'Strategic HR partnership',
      },
      {
        id: 'people_ops',
        title: 'People Operations Specialist',
        ukAverageSalary: 40000,
        remoteability: 'hybrid',
        demandTrend: 'growing',
        visaSponsorship: 'rare',
        freelanceViable: false,
        description: 'Employee experience and operations',
      },
      {
        id: 'learning_development',
        title: 'L&D Specialist',
        ukAverageSalary: 42000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Training and development programs',
      },
    ],
  },
  {
    id: 'consulting',
    name: 'Consulting & Strategy',
    icon: '🎯',
    description: 'Management consulting and strategic advisory',
    jobs: [
      {
        id: 'management_consultant',
        title: 'Management Consultant',
        ukAverageSalary: 60000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'common',
        freelanceViable: true,
        description: 'Business strategy and transformation',
      },
      {
        id: 'strategy_consultant',
        title: 'Strategy Consultant',
        ukAverageSalary: 70000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'common',
        freelanceViable: true,
        description: 'Corporate strategy development',
      },
      {
        id: 'it_consultant',
        title: 'IT Consultant',
        ukAverageSalary: 55000,
        remoteability: 'hybrid',
        demandTrend: 'growing',
        visaSponsorship: 'common',
        freelanceViable: true,
        description: 'Technology advisory and implementation',
      },
      {
        id: 'business_analyst',
        title: 'Business Analyst',
        ukAverageSalary: 48000,
        remoteability: 'hybrid',
        demandTrend: 'growing',
        visaSponsorship: 'possible',
        freelanceViable: true,
        description: 'Process analysis and requirements',
      },
      {
        id: 'freelance_consultant',
        title: 'Freelance Consultant',
        ukAverageSalary: 65000,
        remoteability: 'fully_remote',
        demandTrend: 'growing',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Independent advisory services',
      },
    ],
  },
  {
    id: 'operations',
    name: 'Operations & Project Management',
    icon: '⚙️',
    description: 'Operations, logistics, and project delivery',
    jobs: [
      {
        id: 'project_manager',
        title: 'Project Manager',
        ukAverageSalary: 52000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'possible',
        freelanceViable: true,
        description: 'Project planning and delivery',
      },
      {
        id: 'program_manager',
        title: 'Program Manager',
        ukAverageSalary: 65000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'possible',
        freelanceViable: true,
        description: 'Multi-project portfolio management',
      },
      {
        id: 'scrum_master',
        title: 'Scrum Master',
        ukAverageSalary: 55000,
        remoteability: 'fully_remote',
        demandTrend: 'growing',
        visaSponsorship: 'possible',
        freelanceViable: true,
        description: 'Agile team facilitation',
      },
      {
        id: 'operations_manager',
        title: 'Operations Manager',
        ukAverageSalary: 50000,
        remoteability: 'on_site',
        demandTrend: 'stable',
        visaSponsorship: 'possible',
        freelanceViable: false,
        description: 'Day-to-day operations management',
      },
      {
        id: 'supply_chain',
        title: 'Supply Chain Manager',
        ukAverageSalary: 55000,
        remoteability: 'on_site',
        demandTrend: 'stable',
        visaSponsorship: 'possible',
        freelanceViable: false,
        description: 'Supply chain and logistics',
      },
    ],
  },
  {
    id: 'legal',
    name: 'Legal',
    icon: '⚖️',
    description: 'Legal services and compliance',
    jobs: [
      {
        id: 'lawyer',
        title: 'Solicitor/Lawyer',
        ukAverageSalary: 60000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'possible',
        freelanceViable: true,
        description: 'Legal advice and representation',
      },
      {
        id: 'paralegal',
        title: 'Paralegal',
        ukAverageSalary: 32000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Legal research and support',
      },
      {
        id: 'legal_counsel',
        title: 'In-House Legal Counsel',
        ukAverageSalary: 75000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'possible',
        freelanceViable: false,
        description: 'Corporate legal advice',
      },
      {
        id: 'compliance_officer',
        title: 'Compliance Officer',
        ukAverageSalary: 55000,
        remoteability: 'hybrid',
        demandTrend: 'growing',
        visaSponsorship: 'possible',
        freelanceViable: true,
        description: 'Regulatory compliance',
      },
      {
        id: 'contract_manager',
        title: 'Contract Manager',
        ukAverageSalary: 50000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Contract negotiation and management',
      },
    ],
  },
  {
    id: 'healthcare',
    name: 'Healthcare',
    icon: '🏥',
    description: 'Medical and health-related professions',
    jobs: [
      {
        id: 'doctor',
        title: 'Doctor/Physician',
        ukAverageSalary: 80000,
        remoteability: 'on_site',
        demandTrend: 'high_growth',
        visaSponsorship: 'common',
        freelanceViable: false,
        description: 'Medical diagnosis and treatment',
      },
      {
        id: 'nurse',
        title: 'Nurse',
        ukAverageSalary: 35000,
        remoteability: 'on_site',
        demandTrend: 'high_growth',
        visaSponsorship: 'common',
        freelanceViable: false,
        description: 'Patient care and support',
      },
      {
        id: 'pharmacist',
        title: 'Pharmacist',
        ukAverageSalary: 45000,
        remoteability: 'on_site',
        demandTrend: 'stable',
        visaSponsorship: 'possible',
        freelanceViable: false,
        description: 'Medication dispensing and advice',
      },
      {
        id: 'physiotherapist',
        title: 'Physiotherapist',
        ukAverageSalary: 38000,
        remoteability: 'on_site',
        demandTrend: 'growing',
        visaSponsorship: 'possible',
        freelanceViable: true,
        description: 'Physical rehabilitation',
      },
      {
        id: 'psychologist',
        title: 'Psychologist',
        ukAverageSalary: 45000,
        remoteability: 'hybrid',
        demandTrend: 'growing',
        visaSponsorship: 'possible',
        freelanceViable: true,
        description: 'Mental health support',
      },
      {
        id: 'health_admin',
        title: 'Healthcare Administrator',
        ukAverageSalary: 42000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'rare',
        freelanceViable: false,
        description: 'Healthcare operations management',
      },
    ],
  },
  {
    id: 'education',
    name: 'Education & Training',
    icon: '📚',
    description: 'Teaching, training, and educational content',
    jobs: [
      {
        id: 'teacher',
        title: 'Teacher',
        ukAverageSalary: 32000,
        remoteability: 'on_site',
        demandTrend: 'stable',
        visaSponsorship: 'common',
        freelanceViable: false,
        description: 'Classroom teaching',
      },
      {
        id: 'university_lecturer',
        title: 'University Lecturer',
        ukAverageSalary: 48000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'common',
        freelanceViable: true,
        description: 'Higher education teaching',
      },
      {
        id: 'online_tutor',
        title: 'Online Tutor',
        ukAverageSalary: 28000,
        remoteability: 'fully_remote',
        demandTrend: 'high_growth',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Remote tutoring and teaching',
      },
      {
        id: 'instructional_designer',
        title: 'Instructional Designer',
        ukAverageSalary: 42000,
        remoteability: 'fully_remote',
        demandTrend: 'growing',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'E-learning course design',
      },
      {
        id: 'corporate_trainer',
        title: 'Corporate Trainer',
        ukAverageSalary: 45000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Business training delivery',
      },
      {
        id: 'tefl_teacher',
        title: 'TEFL/English Teacher',
        ukAverageSalary: 25000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'common',
        freelanceViable: true,
        description: 'English language teaching',
      },
    ],
  },
  {
    id: 'creative',
    name: 'Creative & Entertainment',
    icon: '🎬',
    description: 'Arts, entertainment, and creative industries',
    jobs: [
      {
        id: 'photographer',
        title: 'Photographer',
        ukAverageSalary: 28000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Professional photography',
      },
      {
        id: 'videographer',
        title: 'Videographer',
        ukAverageSalary: 32000,
        remoteability: 'hybrid',
        demandTrend: 'growing',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Video filming and production',
      },
      {
        id: 'animator',
        title: 'Animator',
        ukAverageSalary: 35000,
        remoteability: 'fully_remote',
        demandTrend: 'growing',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: '2D/3D animation',
      },
      {
        id: 'game_designer',
        title: 'Game Designer',
        ukAverageSalary: 42000,
        remoteability: 'hybrid',
        demandTrend: 'growing',
        visaSponsorship: 'possible',
        freelanceViable: true,
        description: 'Video game design',
      },
      {
        id: 'musician',
        title: 'Musician/Producer',
        ukAverageSalary: 25000,
        remoteability: 'fully_remote',
        demandTrend: 'stable',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Music creation and production',
      },
      {
        id: 'voice_actor',
        title: 'Voice Actor',
        ukAverageSalary: 30000,
        remoteability: 'fully_remote',
        demandTrend: 'growing',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Voice over and narration',
      },
    ],
  },
  {
    id: 'customer_service',
    name: 'Customer Service & Support',
    icon: '📞',
    description: 'Customer support and service roles',
    jobs: [
      {
        id: 'customer_service_rep',
        title: 'Customer Service Rep',
        ukAverageSalary: 24000,
        remoteability: 'fully_remote',
        demandTrend: 'stable',
        visaSponsorship: 'rare',
        freelanceViable: false,
        description: 'Customer inquiries and support',
      },
      {
        id: 'technical_support',
        title: 'Technical Support',
        ukAverageSalary: 28000,
        remoteability: 'fully_remote',
        demandTrend: 'stable',
        visaSponsorship: 'rare',
        freelanceViable: false,
        description: 'Technical product support',
      },
      {
        id: 'customer_service_manager',
        title: 'Customer Service Manager',
        ukAverageSalary: 38000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'rare',
        freelanceViable: false,
        description: 'Support team management',
      },
      {
        id: 'community_manager',
        title: 'Community Manager',
        ukAverageSalary: 35000,
        remoteability: 'fully_remote',
        demandTrend: 'growing',
        visaSponsorship: 'rare',
        freelanceViable: true,
        description: 'Online community engagement',
      },
    ],
  },
  {
    id: 'other',
    name: 'Other / Custom',
    icon: '📋',
    description: 'Other professions not listed above',
    jobs: [
      {
        id: 'custom',
        title: 'Custom Role',
        ukAverageSalary: 40000,
        remoteability: 'hybrid',
        demandTrend: 'stable',
        visaSponsorship: 'possible',
        freelanceViable: true,
        description: 'Enter your own salary',
      },
    ],
  },
];

// Helper function to get all jobs flat
export function getAllJobs(): { job: Job; industry: Industry }[] {
  return INDUSTRIES.flatMap(industry =>
    industry.jobs.map(job => ({ job, industry }))
  );
}

// Helper function to get job by ID
export function getJobById(jobId: string): { job: Job; industry: Industry } | undefined {
  for (const industry of INDUSTRIES) {
    const job = industry.jobs.find(j => j.id === jobId);
    if (job) {
      return { job, industry };
    }
  }
  return undefined;
}

// Labels for display
export const REMOTEABILITY_LABELS: Record<Job['remoteability'], { label: string; color: string; icon: string }> = {
  fully_remote: { label: 'Fully Remote', color: 'text-green-400 bg-green-500/20', icon: '🌍' },
  hybrid: { label: 'Hybrid', color: 'text-yellow-400 bg-yellow-500/20', icon: '🏢' },
  on_site: { label: 'On-Site Only', color: 'text-red-400 bg-red-500/20', icon: '📍' },
};

export const DEMAND_LABELS: Record<Job['demandTrend'], { label: string; color: string }> = {
  high_growth: { label: 'High Growth', color: 'text-emerald-400' },
  growing: { label: 'Growing', color: 'text-green-400' },
  stable: { label: 'Stable', color: 'text-blue-400' },
  declining: { label: 'Declining', color: 'text-orange-400' },
};

export const VISA_LABELS: Record<Job['visaSponsorship'], { label: string; color: string }> = {
  common: { label: 'Common', color: 'text-green-400' },
  possible: { label: 'Possible', color: 'text-yellow-400' },
  rare: { label: 'Rare', color: 'text-red-400' },
};
