// Comprehensive location database for Geographic Arbitrage Calculator
// 80+ cities worldwide with cost of living, lifestyle, and job data

export type LocationType = 'uk' | 'europe' | 'americas' | 'asia' | 'middle_east' | 'oceania' | 'africa';

export interface Location {
  id: string;
  name: string;
  country: string;
  region: LocationType;
  flag: string;
  // Cost indices relative to UK average (100 = UK average)
  housingIndex: number;
  transportIndex: number;
  groceriesIndex: number;
  utilitiesIndex: number;
  entertainmentIndex: number;
  healthcareIndex: number;
  // Lifestyle metrics (1-10)
  safetyRating: number;
  healthcareQuality: number;
  climateRating: number;
  englishProficiency: number;
  internetSpeed: number;
  workLifeBalance: number;
  // Housing
  avgRent1Bed: number;
  avgRent2Bed: number;
  // Visa/legal
  visaEase: 'easy' | 'moderate' | 'difficult';
  digitalNomadVisa: boolean;
  retirementVisa: boolean;
  // Tax
  incomeTaxRate: number;
  capitalGainsTax: number;
  // Links
  nomadListUrl?: string;
  expatInfoUrl?: string;
  jobSearchUrls: { name: string; url: string }[];
  // Popular for
  popularFor: string[];
}

// ============================================
// UK LOCATIONS
// ============================================
export const UK_LOCATIONS: Location[] = [
  {
    id: 'london',
    name: 'London',
    country: 'United Kingdom',
    region: 'uk',
    flag: '🇬🇧',
    housingIndex: 175,
    transportIndex: 130,
    groceriesIndex: 108,
    utilitiesIndex: 105,
    entertainmentIndex: 125,
    healthcareIndex: 100,
    safetyRating: 7,
    healthcareQuality: 8,
    climateRating: 5,
    englishProficiency: 10,
    internetSpeed: 80,
    workLifeBalance: 5,
    avgRent1Bed: 1800,
    avgRent2Bed: 2400,
    visaEase: 'easy',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 32,
    capitalGainsTax: 20,
    jobSearchUrls: [
      { name: 'LinkedIn UK', url: 'https://www.linkedin.com/jobs/search/?location=London' },
      { name: 'Indeed UK', url: 'https://uk.indeed.com/jobs?l=London' },
      { name: 'Reed', url: 'https://www.reed.co.uk/jobs/in-london' },
    ],
    popularFor: ['Finance', 'Tech', 'Media', 'Fashion'],
  },
  {
    id: 'manchester',
    name: 'Manchester',
    country: 'United Kingdom',
    region: 'uk',
    flag: '🇬🇧',
    housingIndex: 90,
    transportIndex: 95,
    groceriesIndex: 97,
    utilitiesIndex: 96,
    entertainmentIndex: 92,
    healthcareIndex: 100,
    safetyRating: 7,
    healthcareQuality: 8,
    climateRating: 4,
    englishProficiency: 10,
    internetSpeed: 75,
    workLifeBalance: 7,
    avgRent1Bed: 850,
    avgRent2Bed: 1100,
    visaEase: 'easy',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 32,
    capitalGainsTax: 20,
    jobSearchUrls: [
      { name: 'LinkedIn UK', url: 'https://www.linkedin.com/jobs/search/?location=Manchester' },
      { name: 'Indeed UK', url: 'https://uk.indeed.com/jobs?l=Manchester' },
    ],
    popularFor: ['Tech', 'Media', 'Music', 'Sports'],
  },
  {
    id: 'birmingham',
    name: 'Birmingham',
    country: 'United Kingdom',
    region: 'uk',
    flag: '🇬🇧',
    housingIndex: 85,
    transportIndex: 90,
    groceriesIndex: 95,
    utilitiesIndex: 94,
    entertainmentIndex: 88,
    healthcareIndex: 100,
    safetyRating: 6,
    healthcareQuality: 8,
    climateRating: 5,
    englishProficiency: 10,
    internetSpeed: 70,
    workLifeBalance: 7,
    avgRent1Bed: 750,
    avgRent2Bed: 950,
    visaEase: 'easy',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 32,
    capitalGainsTax: 20,
    jobSearchUrls: [
      { name: 'LinkedIn UK', url: 'https://www.linkedin.com/jobs/search/?location=Birmingham' },
    ],
    popularFor: ['Manufacturing', 'Finance', 'Healthcare'],
  },
  {
    id: 'edinburgh',
    name: 'Edinburgh',
    country: 'United Kingdom',
    region: 'uk',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    housingIndex: 95,
    transportIndex: 95,
    groceriesIndex: 98,
    utilitiesIndex: 98,
    entertainmentIndex: 95,
    healthcareIndex: 100,
    safetyRating: 8,
    healthcareQuality: 9,
    climateRating: 4,
    englishProficiency: 10,
    internetSpeed: 70,
    workLifeBalance: 7,
    avgRent1Bed: 950,
    avgRent2Bed: 1250,
    visaEase: 'easy',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 32,
    capitalGainsTax: 20,
    jobSearchUrls: [
      { name: 'LinkedIn UK', url: 'https://www.linkedin.com/jobs/search/?location=Edinburgh' },
      { name: 's1jobs', url: 'https://www.s1jobs.com/jobs/edinburgh/' },
    ],
    popularFor: ['Finance', 'Tech', 'Tourism', 'Education'],
  },
  {
    id: 'glasgow',
    name: 'Glasgow',
    country: 'United Kingdom',
    region: 'uk',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    housingIndex: 75,
    transportIndex: 85,
    groceriesIndex: 95,
    utilitiesIndex: 95,
    entertainmentIndex: 85,
    healthcareIndex: 100,
    safetyRating: 6,
    healthcareQuality: 8,
    climateRating: 3,
    englishProficiency: 10,
    internetSpeed: 68,
    workLifeBalance: 7,
    avgRent1Bed: 700,
    avgRent2Bed: 900,
    visaEase: 'easy',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 32,
    capitalGainsTax: 20,
    jobSearchUrls: [
      { name: 'LinkedIn UK', url: 'https://www.linkedin.com/jobs/search/?location=Glasgow' },
    ],
    popularFor: ['Shipbuilding', 'Tech', 'Arts', 'Music'],
  },
  {
    id: 'bristol',
    name: 'Bristol',
    country: 'United Kingdom',
    region: 'uk',
    flag: '🇬🇧',
    housingIndex: 110,
    transportIndex: 100,
    groceriesIndex: 100,
    utilitiesIndex: 98,
    entertainmentIndex: 100,
    healthcareIndex: 100,
    safetyRating: 7,
    healthcareQuality: 8,
    climateRating: 6,
    englishProficiency: 10,
    internetSpeed: 72,
    workLifeBalance: 7,
    avgRent1Bed: 1000,
    avgRent2Bed: 1300,
    visaEase: 'easy',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 32,
    capitalGainsTax: 20,
    jobSearchUrls: [
      { name: 'LinkedIn UK', url: 'https://www.linkedin.com/jobs/search/?location=Bristol' },
    ],
    popularFor: ['Aerospace', 'Tech', 'Creative', 'Green Energy'],
  },
  {
    id: 'leeds',
    name: 'Leeds',
    country: 'United Kingdom',
    region: 'uk',
    flag: '🇬🇧',
    housingIndex: 80,
    transportIndex: 88,
    groceriesIndex: 94,
    utilitiesIndex: 93,
    entertainmentIndex: 85,
    healthcareIndex: 100,
    safetyRating: 7,
    healthcareQuality: 8,
    climateRating: 4,
    englishProficiency: 10,
    internetSpeed: 68,
    workLifeBalance: 7,
    avgRent1Bed: 750,
    avgRent2Bed: 950,
    visaEase: 'easy',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 32,
    capitalGainsTax: 20,
    jobSearchUrls: [
      { name: 'LinkedIn UK', url: 'https://www.linkedin.com/jobs/search/?location=Leeds' },
    ],
    popularFor: ['Finance', 'Legal', 'Healthcare', 'Digital'],
  },
  {
    id: 'liverpool',
    name: 'Liverpool',
    country: 'United Kingdom',
    region: 'uk',
    flag: '🇬🇧',
    housingIndex: 70,
    transportIndex: 85,
    groceriesIndex: 92,
    utilitiesIndex: 92,
    entertainmentIndex: 82,
    healthcareIndex: 100,
    safetyRating: 6,
    healthcareQuality: 8,
    climateRating: 4,
    englishProficiency: 10,
    internetSpeed: 65,
    workLifeBalance: 7,
    avgRent1Bed: 650,
    avgRent2Bed: 850,
    visaEase: 'easy',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 32,
    capitalGainsTax: 20,
    jobSearchUrls: [
      { name: 'LinkedIn UK', url: 'https://www.linkedin.com/jobs/search/?location=Liverpool' },
    ],
    popularFor: ['Maritime', 'Tourism', 'Creative', 'Music'],
  },
  {
    id: 'newcastle',
    name: 'Newcastle',
    country: 'United Kingdom',
    region: 'uk',
    flag: '🇬🇧',
    housingIndex: 70,
    transportIndex: 82,
    groceriesIndex: 92,
    utilitiesIndex: 91,
    entertainmentIndex: 80,
    healthcareIndex: 100,
    safetyRating: 7,
    healthcareQuality: 8,
    climateRating: 4,
    englishProficiency: 10,
    internetSpeed: 65,
    workLifeBalance: 7,
    avgRent1Bed: 600,
    avgRent2Bed: 780,
    visaEase: 'easy',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 32,
    capitalGainsTax: 20,
    jobSearchUrls: [
      { name: 'LinkedIn UK', url: 'https://www.linkedin.com/jobs/search/?location=Newcastle' },
    ],
    popularFor: ['Tech', 'Education', 'Healthcare', 'Retail'],
  },
  {
    id: 'cardiff',
    name: 'Cardiff',
    country: 'United Kingdom',
    region: 'uk',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    housingIndex: 75,
    transportIndex: 85,
    groceriesIndex: 93,
    utilitiesIndex: 92,
    entertainmentIndex: 82,
    healthcareIndex: 100,
    safetyRating: 7,
    healthcareQuality: 8,
    climateRating: 5,
    englishProficiency: 10,
    internetSpeed: 65,
    workLifeBalance: 7,
    avgRent1Bed: 700,
    avgRent2Bed: 900,
    visaEase: 'easy',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 32,
    capitalGainsTax: 20,
    jobSearchUrls: [
      { name: 'LinkedIn UK', url: 'https://www.linkedin.com/jobs/search/?location=Cardiff' },
    ],
    popularFor: ['Media', 'Government', 'Finance', 'Tourism'],
  },
  {
    id: 'belfast',
    name: 'Belfast',
    country: 'United Kingdom',
    region: 'uk',
    flag: '🇬🇧',
    housingIndex: 65,
    transportIndex: 80,
    groceriesIndex: 95,
    utilitiesIndex: 92,
    entertainmentIndex: 78,
    healthcareIndex: 100,
    safetyRating: 7,
    healthcareQuality: 8,
    climateRating: 4,
    englishProficiency: 10,
    internetSpeed: 60,
    workLifeBalance: 7,
    avgRent1Bed: 600,
    avgRent2Bed: 780,
    visaEase: 'easy',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 32,
    capitalGainsTax: 20,
    jobSearchUrls: [
      { name: 'LinkedIn UK', url: 'https://www.linkedin.com/jobs/search/?location=Belfast' },
    ],
    popularFor: ['Tech', 'Finance', 'Tourism', 'Aerospace'],
  },
  {
    id: 'cambridge',
    name: 'Cambridge',
    country: 'United Kingdom',
    region: 'uk',
    flag: '🇬🇧',
    housingIndex: 130,
    transportIndex: 100,
    groceriesIndex: 102,
    utilitiesIndex: 100,
    entertainmentIndex: 105,
    healthcareIndex: 100,
    safetyRating: 9,
    healthcareQuality: 9,
    climateRating: 5,
    englishProficiency: 10,
    internetSpeed: 85,
    workLifeBalance: 7,
    avgRent1Bed: 1200,
    avgRent2Bed: 1600,
    visaEase: 'easy',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 32,
    capitalGainsTax: 20,
    jobSearchUrls: [
      { name: 'LinkedIn UK', url: 'https://www.linkedin.com/jobs/search/?location=Cambridge' },
    ],
    popularFor: ['Biotech', 'Tech', 'Education', 'Research'],
  },
  {
    id: 'oxford',
    name: 'Oxford',
    country: 'United Kingdom',
    region: 'uk',
    flag: '🇬🇧',
    housingIndex: 135,
    transportIndex: 100,
    groceriesIndex: 103,
    utilitiesIndex: 100,
    entertainmentIndex: 105,
    healthcareIndex: 100,
    safetyRating: 8,
    healthcareQuality: 9,
    climateRating: 5,
    englishProficiency: 10,
    internetSpeed: 80,
    workLifeBalance: 7,
    avgRent1Bed: 1250,
    avgRent2Bed: 1650,
    visaEase: 'easy',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 32,
    capitalGainsTax: 20,
    jobSearchUrls: [
      { name: 'LinkedIn UK', url: 'https://www.linkedin.com/jobs/search/?location=Oxford' },
    ],
    popularFor: ['Education', 'Publishing', 'Research', 'Tech'],
  },
  {
    id: 'brighton',
    name: 'Brighton',
    country: 'United Kingdom',
    region: 'uk',
    flag: '🇬🇧',
    housingIndex: 115,
    transportIndex: 105,
    groceriesIndex: 102,
    utilitiesIndex: 100,
    entertainmentIndex: 110,
    healthcareIndex: 100,
    safetyRating: 7,
    healthcareQuality: 8,
    climateRating: 6,
    englishProficiency: 10,
    internetSpeed: 75,
    workLifeBalance: 8,
    avgRent1Bed: 1100,
    avgRent2Bed: 1450,
    visaEase: 'easy',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 32,
    capitalGainsTax: 20,
    jobSearchUrls: [
      { name: 'LinkedIn UK', url: 'https://www.linkedin.com/jobs/search/?location=Brighton' },
    ],
    popularFor: ['Tech', 'Creative', 'Tourism', 'LGBTQ+'],
  },
];

// ============================================
// EUROPEAN LOCATIONS
// ============================================
export const EUROPE_LOCATIONS: Location[] = [
  // Portugal
  {
    id: 'lisbon',
    name: 'Lisbon',
    country: 'Portugal',
    region: 'europe',
    flag: '🇵🇹',
    housingIndex: 80,
    transportIndex: 55,
    groceriesIndex: 65,
    utilitiesIndex: 70,
    entertainmentIndex: 55,
    healthcareIndex: 50,
    safetyRating: 9,
    healthcareQuality: 8,
    climateRating: 9,
    englishProficiency: 7,
    internetSpeed: 100,
    workLifeBalance: 8,
    avgRent1Bed: 950,
    avgRent2Bed: 1300,
    visaEase: 'moderate',
    digitalNomadVisa: true,
    retirementVisa: true,
    incomeTaxRate: 28,
    capitalGainsTax: 28,
    nomadListUrl: 'https://nomadlist.com/lisbon',
    expatInfoUrl: 'https://www.expatfocus.com/expatriate-portugal',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Lisbon' },
      { name: 'Landing.jobs', url: 'https://landing.jobs/jobs?location=Lisbon' },
    ],
    popularFor: ['Tech Startups', 'Digital Nomads', 'Surfing', 'Wine'],
  },
  {
    id: 'porto',
    name: 'Porto',
    country: 'Portugal',
    region: 'europe',
    flag: '🇵🇹',
    housingIndex: 65,
    transportIndex: 50,
    groceriesIndex: 60,
    utilitiesIndex: 65,
    entertainmentIndex: 50,
    healthcareIndex: 48,
    safetyRating: 9,
    healthcareQuality: 8,
    climateRating: 8,
    englishProficiency: 6,
    internetSpeed: 90,
    workLifeBalance: 8,
    avgRent1Bed: 700,
    avgRent2Bed: 950,
    visaEase: 'moderate',
    digitalNomadVisa: true,
    retirementVisa: true,
    incomeTaxRate: 28,
    capitalGainsTax: 28,
    nomadListUrl: 'https://nomadlist.com/porto',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Porto' },
    ],
    popularFor: ['Wine', 'Tourism', 'Tech', 'History'],
  },
  // Spain
  {
    id: 'barcelona',
    name: 'Barcelona',
    country: 'Spain',
    region: 'europe',
    flag: '🇪🇸',
    housingIndex: 90,
    transportIndex: 60,
    groceriesIndex: 65,
    utilitiesIndex: 75,
    entertainmentIndex: 60,
    healthcareIndex: 55,
    safetyRating: 8,
    healthcareQuality: 9,
    climateRating: 9,
    englishProficiency: 6,
    internetSpeed: 95,
    workLifeBalance: 8,
    avgRent1Bed: 1000,
    avgRent2Bed: 1400,
    visaEase: 'moderate',
    digitalNomadVisa: true,
    retirementVisa: true,
    incomeTaxRate: 35,
    capitalGainsTax: 23,
    nomadListUrl: 'https://nomadlist.com/barcelona',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Barcelona' },
      { name: 'InfoJobs', url: 'https://www.infojobs.net/ofertas-trabajo/barcelona' },
    ],
    popularFor: ['Design', 'Tech', 'Tourism', 'Architecture'],
  },
  {
    id: 'madrid',
    name: 'Madrid',
    country: 'Spain',
    region: 'europe',
    flag: '🇪🇸',
    housingIndex: 85,
    transportIndex: 55,
    groceriesIndex: 62,
    utilitiesIndex: 70,
    entertainmentIndex: 58,
    healthcareIndex: 55,
    safetyRating: 8,
    healthcareQuality: 9,
    climateRating: 8,
    englishProficiency: 5,
    internetSpeed: 100,
    workLifeBalance: 8,
    avgRent1Bed: 900,
    avgRent2Bed: 1250,
    visaEase: 'moderate',
    digitalNomadVisa: true,
    retirementVisa: true,
    incomeTaxRate: 35,
    capitalGainsTax: 23,
    nomadListUrl: 'https://nomadlist.com/madrid',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Madrid' },
    ],
    popularFor: ['Finance', 'Art', 'Culture', 'Food'],
  },
  {
    id: 'valencia',
    name: 'Valencia',
    country: 'Spain',
    region: 'europe',
    flag: '🇪🇸',
    housingIndex: 65,
    transportIndex: 50,
    groceriesIndex: 58,
    utilitiesIndex: 68,
    entertainmentIndex: 52,
    healthcareIndex: 52,
    safetyRating: 8,
    healthcareQuality: 8,
    climateRating: 9,
    englishProficiency: 5,
    internetSpeed: 90,
    workLifeBalance: 9,
    avgRent1Bed: 700,
    avgRent2Bed: 950,
    visaEase: 'moderate',
    digitalNomadVisa: true,
    retirementVisa: true,
    incomeTaxRate: 35,
    capitalGainsTax: 23,
    nomadListUrl: 'https://nomadlist.com/valencia',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Valencia' },
    ],
    popularFor: ['Beach', 'Paella', 'Tech', 'Expats'],
  },
  {
    id: 'malaga',
    name: 'Málaga',
    country: 'Spain',
    region: 'europe',
    flag: '🇪🇸',
    housingIndex: 60,
    transportIndex: 48,
    groceriesIndex: 55,
    utilitiesIndex: 65,
    entertainmentIndex: 50,
    healthcareIndex: 50,
    safetyRating: 8,
    healthcareQuality: 8,
    climateRating: 10,
    englishProficiency: 5,
    internetSpeed: 85,
    workLifeBalance: 9,
    avgRent1Bed: 650,
    avgRent2Bed: 900,
    visaEase: 'moderate',
    digitalNomadVisa: true,
    retirementVisa: true,
    incomeTaxRate: 35,
    capitalGainsTax: 23,
    nomadListUrl: 'https://nomadlist.com/malaga',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Malaga' },
    ],
    popularFor: ['Beach', 'Retirement', 'Tourism', 'Art'],
  },
  // Germany
  {
    id: 'berlin',
    name: 'Berlin',
    country: 'Germany',
    region: 'europe',
    flag: '🇩🇪',
    housingIndex: 95,
    transportIndex: 75,
    groceriesIndex: 75,
    utilitiesIndex: 90,
    entertainmentIndex: 70,
    healthcareIndex: 85,
    safetyRating: 8,
    healthcareQuality: 9,
    climateRating: 5,
    englishProficiency: 8,
    internetSpeed: 85,
    workLifeBalance: 8,
    avgRent1Bed: 1100,
    avgRent2Bed: 1500,
    visaEase: 'moderate',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 42,
    capitalGainsTax: 26,
    nomadListUrl: 'https://nomadlist.com/berlin',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Berlin' },
      { name: 'Berlin Startup Jobs', url: 'https://berlinstartupjobs.com' },
    ],
    popularFor: ['Tech Startups', 'Music', 'Art', 'Nightlife'],
  },
  {
    id: 'munich',
    name: 'Munich',
    country: 'Germany',
    region: 'europe',
    flag: '🇩🇪',
    housingIndex: 130,
    transportIndex: 85,
    groceriesIndex: 80,
    utilitiesIndex: 95,
    entertainmentIndex: 85,
    healthcareIndex: 90,
    safetyRating: 9,
    healthcareQuality: 10,
    climateRating: 6,
    englishProficiency: 7,
    internetSpeed: 90,
    workLifeBalance: 8,
    avgRent1Bed: 1400,
    avgRent2Bed: 1900,
    visaEase: 'moderate',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 42,
    capitalGainsTax: 26,
    nomadListUrl: 'https://nomadlist.com/munich',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Munich' },
    ],
    popularFor: ['Automotive', 'Finance', 'Tech', 'Beer'],
  },
  // Netherlands
  {
    id: 'amsterdam',
    name: 'Amsterdam',
    country: 'Netherlands',
    region: 'europe',
    flag: '🇳🇱',
    housingIndex: 130,
    transportIndex: 80,
    groceriesIndex: 80,
    utilitiesIndex: 95,
    entertainmentIndex: 85,
    healthcareIndex: 90,
    safetyRating: 9,
    healthcareQuality: 9,
    climateRating: 5,
    englishProficiency: 9,
    internetSpeed: 100,
    workLifeBalance: 9,
    avgRent1Bed: 1500,
    avgRent2Bed: 2000,
    visaEase: 'moderate',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 40,
    capitalGainsTax: 30,
    nomadListUrl: 'https://nomadlist.com/amsterdam',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Amsterdam' },
    ],
    popularFor: ['Tech', 'Finance', 'Creative', 'Cycling'],
  },
  // France
  {
    id: 'paris',
    name: 'Paris',
    country: 'France',
    region: 'europe',
    flag: '🇫🇷',
    housingIndex: 150,
    transportIndex: 85,
    groceriesIndex: 85,
    utilitiesIndex: 90,
    entertainmentIndex: 95,
    healthcareIndex: 85,
    safetyRating: 7,
    healthcareQuality: 9,
    climateRating: 6,
    englishProficiency: 5,
    internetSpeed: 90,
    workLifeBalance: 7,
    avgRent1Bed: 1400,
    avgRent2Bed: 1900,
    visaEase: 'moderate',
    digitalNomadVisa: false,
    retirementVisa: true,
    incomeTaxRate: 45,
    capitalGainsTax: 30,
    nomadListUrl: 'https://nomadlist.com/paris',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Paris' },
    ],
    popularFor: ['Fashion', 'Art', 'Finance', 'Luxury'],
  },
  {
    id: 'nice',
    name: 'Nice',
    country: 'France',
    region: 'europe',
    flag: '🇫🇷',
    housingIndex: 100,
    transportIndex: 70,
    groceriesIndex: 80,
    utilitiesIndex: 85,
    entertainmentIndex: 80,
    healthcareIndex: 80,
    safetyRating: 7,
    healthcareQuality: 8,
    climateRating: 9,
    englishProficiency: 5,
    internetSpeed: 85,
    workLifeBalance: 8,
    avgRent1Bed: 950,
    avgRent2Bed: 1300,
    visaEase: 'moderate',
    digitalNomadVisa: false,
    retirementVisa: true,
    incomeTaxRate: 45,
    capitalGainsTax: 30,
    nomadListUrl: 'https://nomadlist.com/nice',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Nice' },
    ],
    popularFor: ['Retirement', 'Tourism', 'Beach', 'Art'],
  },
  // Italy
  {
    id: 'milan',
    name: 'Milan',
    country: 'Italy',
    region: 'europe',
    flag: '🇮🇹',
    housingIndex: 110,
    transportIndex: 70,
    groceriesIndex: 75,
    utilitiesIndex: 85,
    entertainmentIndex: 80,
    healthcareIndex: 75,
    safetyRating: 7,
    healthcareQuality: 8,
    climateRating: 6,
    englishProficiency: 5,
    internetSpeed: 80,
    workLifeBalance: 6,
    avgRent1Bed: 1100,
    avgRent2Bed: 1500,
    visaEase: 'moderate',
    digitalNomadVisa: true,
    retirementVisa: true,
    incomeTaxRate: 43,
    capitalGainsTax: 26,
    nomadListUrl: 'https://nomadlist.com/milan',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Milan' },
    ],
    popularFor: ['Fashion', 'Design', 'Finance', 'Food'],
  },
  {
    id: 'rome',
    name: 'Rome',
    country: 'Italy',
    region: 'europe',
    flag: '🇮🇹',
    housingIndex: 85,
    transportIndex: 65,
    groceriesIndex: 70,
    utilitiesIndex: 80,
    entertainmentIndex: 70,
    healthcareIndex: 70,
    safetyRating: 6,
    healthcareQuality: 7,
    climateRating: 8,
    englishProficiency: 4,
    internetSpeed: 70,
    workLifeBalance: 7,
    avgRent1Bed: 900,
    avgRent2Bed: 1200,
    visaEase: 'moderate',
    digitalNomadVisa: true,
    retirementVisa: true,
    incomeTaxRate: 43,
    capitalGainsTax: 26,
    nomadListUrl: 'https://nomadlist.com/rome',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Rome' },
    ],
    popularFor: ['History', 'Tourism', 'Art', 'Food'],
  },
  // Eastern Europe
  {
    id: 'prague',
    name: 'Prague',
    country: 'Czech Republic',
    region: 'europe',
    flag: '🇨🇿',
    housingIndex: 70,
    transportIndex: 45,
    groceriesIndex: 55,
    utilitiesIndex: 60,
    entertainmentIndex: 45,
    healthcareIndex: 50,
    safetyRating: 9,
    healthcareQuality: 8,
    climateRating: 6,
    englishProficiency: 6,
    internetSpeed: 80,
    workLifeBalance: 8,
    avgRent1Bed: 750,
    avgRent2Bed: 1000,
    visaEase: 'moderate',
    digitalNomadVisa: true,
    retirementVisa: false,
    incomeTaxRate: 23,
    capitalGainsTax: 15,
    nomadListUrl: 'https://nomadlist.com/prague',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Prague' },
    ],
    popularFor: ['Tech', 'Beer', 'History', 'Nightlife'],
  },
  {
    id: 'budapest',
    name: 'Budapest',
    country: 'Hungary',
    region: 'europe',
    flag: '🇭🇺',
    housingIndex: 55,
    transportIndex: 40,
    groceriesIndex: 50,
    utilitiesIndex: 55,
    entertainmentIndex: 40,
    healthcareIndex: 45,
    safetyRating: 8,
    healthcareQuality: 7,
    climateRating: 6,
    englishProficiency: 5,
    internetSpeed: 75,
    workLifeBalance: 7,
    avgRent1Bed: 550,
    avgRent2Bed: 750,
    visaEase: 'moderate',
    digitalNomadVisa: true,
    retirementVisa: false,
    incomeTaxRate: 15,
    capitalGainsTax: 15,
    nomadListUrl: 'https://nomadlist.com/budapest',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Budapest' },
    ],
    popularFor: ['Thermal Baths', 'Nightlife', 'Architecture', 'Affordable'],
  },
  {
    id: 'warsaw',
    name: 'Warsaw',
    country: 'Poland',
    region: 'europe',
    flag: '🇵🇱',
    housingIndex: 60,
    transportIndex: 40,
    groceriesIndex: 50,
    utilitiesIndex: 55,
    entertainmentIndex: 42,
    healthcareIndex: 45,
    safetyRating: 8,
    healthcareQuality: 7,
    climateRating: 5,
    englishProficiency: 6,
    internetSpeed: 85,
    workLifeBalance: 7,
    avgRent1Bed: 600,
    avgRent2Bed: 850,
    visaEase: 'moderate',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 32,
    capitalGainsTax: 19,
    nomadListUrl: 'https://nomadlist.com/warsaw',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Warsaw' },
    ],
    popularFor: ['Tech', 'Finance', 'Startups', 'History'],
  },
  {
    id: 'krakow',
    name: 'Kraków',
    country: 'Poland',
    region: 'europe',
    flag: '🇵🇱',
    housingIndex: 50,
    transportIndex: 35,
    groceriesIndex: 45,
    utilitiesIndex: 50,
    entertainmentIndex: 38,
    healthcareIndex: 42,
    safetyRating: 8,
    healthcareQuality: 7,
    climateRating: 5,
    englishProficiency: 6,
    internetSpeed: 80,
    workLifeBalance: 7,
    avgRent1Bed: 500,
    avgRent2Bed: 700,
    visaEase: 'moderate',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 32,
    capitalGainsTax: 19,
    nomadListUrl: 'https://nomadlist.com/krakow',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Krakow' },
    ],
    popularFor: ['History', 'Culture', 'Tech Outsourcing', 'Students'],
  },
  // Balkans & Mediterranean
  {
    id: 'split',
    name: 'Split',
    country: 'Croatia',
    region: 'europe',
    flag: '🇭🇷',
    housingIndex: 55,
    transportIndex: 45,
    groceriesIndex: 55,
    utilitiesIndex: 55,
    entertainmentIndex: 45,
    healthcareIndex: 40,
    safetyRating: 9,
    healthcareQuality: 7,
    climateRating: 9,
    englishProficiency: 6,
    internetSpeed: 60,
    workLifeBalance: 8,
    avgRent1Bed: 600,
    avgRent2Bed: 850,
    visaEase: 'easy',
    digitalNomadVisa: true,
    retirementVisa: true,
    incomeTaxRate: 30,
    capitalGainsTax: 10,
    nomadListUrl: 'https://nomadlist.com/split',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Split' },
    ],
    popularFor: ['Beach', 'Digital Nomads', 'History', 'Sailing'],
  },
  {
    id: 'dubrovnik',
    name: 'Dubrovnik',
    country: 'Croatia',
    region: 'europe',
    flag: '🇭🇷',
    housingIndex: 70,
    transportIndex: 50,
    groceriesIndex: 60,
    utilitiesIndex: 58,
    entertainmentIndex: 55,
    healthcareIndex: 42,
    safetyRating: 9,
    healthcareQuality: 7,
    climateRating: 9,
    englishProficiency: 6,
    internetSpeed: 55,
    workLifeBalance: 8,
    avgRent1Bed: 750,
    avgRent2Bed: 1000,
    visaEase: 'easy',
    digitalNomadVisa: true,
    retirementVisa: true,
    incomeTaxRate: 30,
    capitalGainsTax: 10,
    nomadListUrl: 'https://nomadlist.com/dubrovnik',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Dubrovnik' },
    ],
    popularFor: ['Tourism', 'Game of Thrones', 'Beach', 'History'],
  },
  {
    id: 'athens',
    name: 'Athens',
    country: 'Greece',
    region: 'europe',
    flag: '🇬🇷',
    housingIndex: 50,
    transportIndex: 45,
    groceriesIndex: 55,
    utilitiesIndex: 60,
    entertainmentIndex: 45,
    healthcareIndex: 45,
    safetyRating: 8,
    healthcareQuality: 7,
    climateRating: 9,
    englishProficiency: 6,
    internetSpeed: 50,
    workLifeBalance: 7,
    avgRent1Bed: 550,
    avgRent2Bed: 750,
    visaEase: 'moderate',
    digitalNomadVisa: true,
    retirementVisa: true,
    incomeTaxRate: 35,
    capitalGainsTax: 15,
    nomadListUrl: 'https://nomadlist.com/athens',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Athens' },
    ],
    popularFor: ['History', 'Islands', 'Food', 'Affordable'],
  },
  // Nordic
  {
    id: 'copenhagen',
    name: 'Copenhagen',
    country: 'Denmark',
    region: 'europe',
    flag: '🇩🇰',
    housingIndex: 140,
    transportIndex: 90,
    groceriesIndex: 95,
    utilitiesIndex: 100,
    entertainmentIndex: 100,
    healthcareIndex: 95,
    safetyRating: 9,
    healthcareQuality: 10,
    climateRating: 4,
    englishProficiency: 9,
    internetSpeed: 110,
    workLifeBalance: 10,
    avgRent1Bed: 1400,
    avgRent2Bed: 1900,
    visaEase: 'difficult',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 55,
    capitalGainsTax: 42,
    nomadListUrl: 'https://nomadlist.com/copenhagen',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Copenhagen' },
    ],
    popularFor: ['Design', 'Sustainability', 'Cycling', 'Hygge'],
  },
  {
    id: 'stockholm',
    name: 'Stockholm',
    country: 'Sweden',
    region: 'europe',
    flag: '🇸🇪',
    housingIndex: 135,
    transportIndex: 85,
    groceriesIndex: 90,
    utilitiesIndex: 95,
    entertainmentIndex: 95,
    healthcareIndex: 95,
    safetyRating: 8,
    healthcareQuality: 10,
    climateRating: 4,
    englishProficiency: 9,
    internetSpeed: 120,
    workLifeBalance: 10,
    avgRent1Bed: 1350,
    avgRent2Bed: 1850,
    visaEase: 'difficult',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 52,
    capitalGainsTax: 30,
    nomadListUrl: 'https://nomadlist.com/stockholm',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Stockholm' },
    ],
    popularFor: ['Tech Unicorns', 'Music', 'Design', 'Nature'],
  },
  // Switzerland
  {
    id: 'zurich',
    name: 'Zurich',
    country: 'Switzerland',
    region: 'europe',
    flag: '🇨🇭',
    housingIndex: 200,
    transportIndex: 120,
    groceriesIndex: 130,
    utilitiesIndex: 110,
    entertainmentIndex: 140,
    healthcareIndex: 150,
    safetyRating: 10,
    healthcareQuality: 10,
    climateRating: 6,
    englishProficiency: 8,
    internetSpeed: 150,
    workLifeBalance: 8,
    avgRent1Bed: 2000,
    avgRent2Bed: 2800,
    visaEase: 'difficult',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 35,
    capitalGainsTax: 0,
    nomadListUrl: 'https://nomadlist.com/zurich',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Zurich' },
    ],
    popularFor: ['Finance', 'Pharma', 'Quality of Life', 'Alps'],
  },
  // Estonia
  {
    id: 'tallinn',
    name: 'Tallinn',
    country: 'Estonia',
    region: 'europe',
    flag: '🇪🇪',
    housingIndex: 55,
    transportIndex: 45,
    groceriesIndex: 55,
    utilitiesIndex: 60,
    entertainmentIndex: 45,
    healthcareIndex: 50,
    safetyRating: 9,
    healthcareQuality: 8,
    climateRating: 4,
    englishProficiency: 8,
    internetSpeed: 100,
    workLifeBalance: 8,
    avgRent1Bed: 600,
    avgRent2Bed: 850,
    visaEase: 'easy',
    digitalNomadVisa: true,
    retirementVisa: false,
    incomeTaxRate: 20,
    capitalGainsTax: 20,
    nomadListUrl: 'https://nomadlist.com/tallinn',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Tallinn' },
    ],
    popularFor: ['e-Residency', 'Startups', 'Digital Nomads', 'Tech'],
  },
];

// ============================================
// AMERICAS LOCATIONS
// ============================================
export const AMERICAS_LOCATIONS: Location[] = [
  // USA
  {
    id: 'nyc',
    name: 'New York City',
    country: 'United States',
    region: 'americas',
    flag: '🇺🇸',
    housingIndex: 230,
    transportIndex: 110,
    groceriesIndex: 112,
    utilitiesIndex: 100,
    entertainmentIndex: 140,
    healthcareIndex: 175,
    safetyRating: 7,
    healthcareQuality: 9,
    climateRating: 6,
    englishProficiency: 10,
    internetSpeed: 120,
    workLifeBalance: 4,
    avgRent1Bed: 2600,
    avgRent2Bed: 3500,
    visaEase: 'difficult',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 40,
    capitalGainsTax: 23,
    nomadListUrl: 'https://nomadlist.com/new-york-city',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=New%20York' },
      { name: 'BuiltInNYC', url: 'https://www.builtinnyc.com/jobs' },
    ],
    popularFor: ['Finance', 'Media', 'Fashion', 'Tech'],
  },
  {
    id: 'sf',
    name: 'San Francisco',
    country: 'United States',
    region: 'americas',
    flag: '🇺🇸',
    housingIndex: 250,
    transportIndex: 120,
    groceriesIndex: 115,
    utilitiesIndex: 95,
    entertainmentIndex: 130,
    healthcareIndex: 180,
    safetyRating: 6,
    healthcareQuality: 9,
    climateRating: 8,
    englishProficiency: 10,
    internetSpeed: 150,
    workLifeBalance: 4,
    avgRent1Bed: 2800,
    avgRent2Bed: 3800,
    visaEase: 'difficult',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 37,
    capitalGainsTax: 23,
    nomadListUrl: 'https://nomadlist.com/san-francisco',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=San%20Francisco' },
      { name: 'AngelList', url: 'https://angel.co/location/san-francisco' },
    ],
    popularFor: ['Tech', 'Startups', 'VC', 'Innovation'],
  },
  {
    id: 'la',
    name: 'Los Angeles',
    country: 'United States',
    region: 'americas',
    flag: '🇺🇸',
    housingIndex: 180,
    transportIndex: 115,
    groceriesIndex: 105,
    utilitiesIndex: 95,
    entertainmentIndex: 120,
    healthcareIndex: 170,
    safetyRating: 6,
    healthcareQuality: 9,
    climateRating: 9,
    englishProficiency: 10,
    internetSpeed: 130,
    workLifeBalance: 5,
    avgRent1Bed: 2000,
    avgRent2Bed: 2700,
    visaEase: 'difficult',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 37,
    capitalGainsTax: 23,
    nomadListUrl: 'https://nomadlist.com/los-angeles',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Los%20Angeles' },
    ],
    popularFor: ['Entertainment', 'Tech', 'Startups', 'Weather'],
  },
  {
    id: 'austin',
    name: 'Austin',
    country: 'United States',
    region: 'americas',
    flag: '🇺🇸',
    housingIndex: 150,
    transportIndex: 100,
    groceriesIndex: 95,
    utilitiesIndex: 90,
    entertainmentIndex: 105,
    healthcareIndex: 160,
    safetyRating: 7,
    healthcareQuality: 8,
    climateRating: 6,
    englishProficiency: 10,
    internetSpeed: 130,
    workLifeBalance: 6,
    avgRent1Bed: 1500,
    avgRent2Bed: 2000,
    visaEase: 'difficult',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 25,
    capitalGainsTax: 20,
    nomadListUrl: 'https://nomadlist.com/austin',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Austin' },
      { name: 'BuiltInAustin', url: 'https://www.builtinaustin.com/jobs' },
    ],
    popularFor: ['Tech', 'Music', 'No State Tax', 'Food'],
  },
  {
    id: 'miami',
    name: 'Miami',
    country: 'United States',
    region: 'americas',
    flag: '🇺🇸',
    housingIndex: 160,
    transportIndex: 105,
    groceriesIndex: 100,
    utilitiesIndex: 95,
    entertainmentIndex: 115,
    healthcareIndex: 165,
    safetyRating: 6,
    healthcareQuality: 8,
    climateRating: 7,
    englishProficiency: 9,
    internetSpeed: 120,
    workLifeBalance: 6,
    avgRent1Bed: 1800,
    avgRent2Bed: 2400,
    visaEase: 'difficult',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 25,
    capitalGainsTax: 20,
    nomadListUrl: 'https://nomadlist.com/miami',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Miami' },
    ],
    popularFor: ['Finance', 'Crypto', 'Latin America HQ', 'Beach'],
  },
  {
    id: 'denver',
    name: 'Denver',
    country: 'United States',
    region: 'americas',
    flag: '🇺🇸',
    housingIndex: 130,
    transportIndex: 95,
    groceriesIndex: 95,
    utilitiesIndex: 88,
    entertainmentIndex: 100,
    healthcareIndex: 155,
    safetyRating: 7,
    healthcareQuality: 8,
    climateRating: 7,
    englishProficiency: 10,
    internetSpeed: 120,
    workLifeBalance: 7,
    avgRent1Bed: 1400,
    avgRent2Bed: 1900,
    visaEase: 'difficult',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 29,
    capitalGainsTax: 20,
    nomadListUrl: 'https://nomadlist.com/denver',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Denver' },
    ],
    popularFor: ['Outdoor', 'Tech', 'Cannabis', 'Skiing'],
  },
  {
    id: 'seattle',
    name: 'Seattle',
    country: 'United States',
    region: 'americas',
    flag: '🇺🇸',
    housingIndex: 170,
    transportIndex: 100,
    groceriesIndex: 105,
    utilitiesIndex: 85,
    entertainmentIndex: 110,
    healthcareIndex: 165,
    safetyRating: 7,
    healthcareQuality: 9,
    climateRating: 5,
    englishProficiency: 10,
    internetSpeed: 140,
    workLifeBalance: 6,
    avgRent1Bed: 1800,
    avgRent2Bed: 2400,
    visaEase: 'difficult',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 25,
    capitalGainsTax: 20,
    nomadListUrl: 'https://nomadlist.com/seattle',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Seattle' },
    ],
    popularFor: ['Tech Giants', 'Coffee', 'Nature', 'No State Tax'],
  },
  // Canada
  {
    id: 'toronto',
    name: 'Toronto',
    country: 'Canada',
    region: 'americas',
    flag: '🇨🇦',
    housingIndex: 140,
    transportIndex: 85,
    groceriesIndex: 90,
    utilitiesIndex: 80,
    entertainmentIndex: 90,
    healthcareIndex: 100,
    safetyRating: 8,
    healthcareQuality: 9,
    climateRating: 4,
    englishProficiency: 10,
    internetSpeed: 100,
    workLifeBalance: 7,
    avgRent1Bed: 1600,
    avgRent2Bed: 2100,
    visaEase: 'moderate',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 43,
    capitalGainsTax: 25,
    nomadListUrl: 'https://nomadlist.com/toronto',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Toronto' },
    ],
    popularFor: ['Finance', 'Tech', 'Diverse', 'Film'],
  },
  {
    id: 'vancouver',
    name: 'Vancouver',
    country: 'Canada',
    region: 'americas',
    flag: '🇨🇦',
    housingIndex: 160,
    transportIndex: 80,
    groceriesIndex: 88,
    utilitiesIndex: 75,
    entertainmentIndex: 88,
    healthcareIndex: 100,
    safetyRating: 8,
    healthcareQuality: 9,
    climateRating: 6,
    englishProficiency: 10,
    internetSpeed: 95,
    workLifeBalance: 8,
    avgRent1Bed: 1700,
    avgRent2Bed: 2300,
    visaEase: 'moderate',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 43,
    capitalGainsTax: 25,
    nomadListUrl: 'https://nomadlist.com/vancouver',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Vancouver' },
    ],
    popularFor: ['Film', 'Tech', 'Nature', 'Asian Gateway'],
  },
  {
    id: 'montreal',
    name: 'Montreal',
    country: 'Canada',
    region: 'americas',
    flag: '🇨🇦',
    housingIndex: 90,
    transportIndex: 70,
    groceriesIndex: 80,
    utilitiesIndex: 70,
    entertainmentIndex: 75,
    healthcareIndex: 100,
    safetyRating: 8,
    healthcareQuality: 9,
    climateRating: 4,
    englishProficiency: 7,
    internetSpeed: 90,
    workLifeBalance: 8,
    avgRent1Bed: 1000,
    avgRent2Bed: 1400,
    visaEase: 'moderate',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 50,
    capitalGainsTax: 25,
    nomadListUrl: 'https://nomadlist.com/montreal',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Montreal' },
    ],
    popularFor: ['AI', 'Gaming', 'Culture', 'Affordable'],
  },
  // Mexico
  {
    id: 'mexico_city',
    name: 'Mexico City',
    country: 'Mexico',
    region: 'americas',
    flag: '🇲🇽',
    housingIndex: 45,
    transportIndex: 35,
    groceriesIndex: 50,
    utilitiesIndex: 40,
    entertainmentIndex: 40,
    healthcareIndex: 35,
    safetyRating: 5,
    healthcareQuality: 7,
    climateRating: 8,
    englishProficiency: 5,
    internetSpeed: 50,
    workLifeBalance: 7,
    avgRent1Bed: 500,
    avgRent2Bed: 750,
    visaEase: 'easy',
    digitalNomadVisa: true,
    retirementVisa: true,
    incomeTaxRate: 30,
    capitalGainsTax: 10,
    nomadListUrl: 'https://nomadlist.com/mexico-city',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Mexico%20City' },
      { name: 'Remote OK', url: 'https://remoteok.com' },
    ],
    popularFor: ['Digital Nomads', 'Food', 'Art', 'Affordable'],
  },
  {
    id: 'playa_del_carmen',
    name: 'Playa del Carmen',
    country: 'Mexico',
    region: 'americas',
    flag: '🇲🇽',
    housingIndex: 50,
    transportIndex: 30,
    groceriesIndex: 55,
    utilitiesIndex: 45,
    entertainmentIndex: 45,
    healthcareIndex: 35,
    safetyRating: 6,
    healthcareQuality: 6,
    climateRating: 8,
    englishProficiency: 6,
    internetSpeed: 40,
    workLifeBalance: 9,
    avgRent1Bed: 600,
    avgRent2Bed: 850,
    visaEase: 'easy',
    digitalNomadVisa: true,
    retirementVisa: true,
    incomeTaxRate: 30,
    capitalGainsTax: 10,
    nomadListUrl: 'https://nomadlist.com/playa-del-carmen',
    jobSearchUrls: [
      { name: 'Remote OK', url: 'https://remoteok.com' },
    ],
    popularFor: ['Beach', 'Digital Nomads', 'Diving', 'Expats'],
  },
  // Colombia
  {
    id: 'medellin',
    name: 'Medellín',
    country: 'Colombia',
    region: 'americas',
    flag: '🇨🇴',
    housingIndex: 35,
    transportIndex: 25,
    groceriesIndex: 40,
    utilitiesIndex: 30,
    entertainmentIndex: 30,
    healthcareIndex: 25,
    safetyRating: 6,
    healthcareQuality: 7,
    climateRating: 9,
    englishProficiency: 4,
    internetSpeed: 45,
    workLifeBalance: 8,
    avgRent1Bed: 400,
    avgRent2Bed: 600,
    visaEase: 'easy',
    digitalNomadVisa: true,
    retirementVisa: true,
    incomeTaxRate: 25,
    capitalGainsTax: 10,
    nomadListUrl: 'https://nomadlist.com/medellin',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Medell%C3%ADn' },
      { name: 'Remote OK', url: 'https://remoteok.com' },
    ],
    popularFor: ['Digital Nomads', 'Climate', 'Affordable', 'Nightlife'],
  },
  {
    id: 'bogota',
    name: 'Bogotá',
    country: 'Colombia',
    region: 'americas',
    flag: '🇨🇴',
    housingIndex: 40,
    transportIndex: 28,
    groceriesIndex: 42,
    utilitiesIndex: 32,
    entertainmentIndex: 32,
    healthcareIndex: 28,
    safetyRating: 5,
    healthcareQuality: 7,
    climateRating: 6,
    englishProficiency: 4,
    internetSpeed: 50,
    workLifeBalance: 7,
    avgRent1Bed: 450,
    avgRent2Bed: 650,
    visaEase: 'easy',
    digitalNomadVisa: true,
    retirementVisa: true,
    incomeTaxRate: 25,
    capitalGainsTax: 10,
    nomadListUrl: 'https://nomadlist.com/bogota',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Bogota' },
    ],
    popularFor: ['Business', 'Culture', 'Food', 'Mountains'],
  },
  // Costa Rica
  {
    id: 'san_jose_cr',
    name: 'San José',
    country: 'Costa Rica',
    region: 'americas',
    flag: '🇨🇷',
    housingIndex: 55,
    transportIndex: 45,
    groceriesIndex: 60,
    utilitiesIndex: 50,
    entertainmentIndex: 50,
    healthcareIndex: 40,
    safetyRating: 7,
    healthcareQuality: 7,
    climateRating: 9,
    englishProficiency: 5,
    internetSpeed: 40,
    workLifeBalance: 9,
    avgRent1Bed: 600,
    avgRent2Bed: 850,
    visaEase: 'moderate',
    digitalNomadVisa: true,
    retirementVisa: true,
    incomeTaxRate: 25,
    capitalGainsTax: 0,
    nomadListUrl: 'https://nomadlist.com/san-jose-costa-rica',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Costa%20Rica' },
    ],
    popularFor: ['Nature', 'Retirement', 'Surfing', 'Eco-tourism'],
  },
  // Argentina
  {
    id: 'buenos_aires',
    name: 'Buenos Aires',
    country: 'Argentina',
    region: 'americas',
    flag: '🇦🇷',
    housingIndex: 35,
    transportIndex: 20,
    groceriesIndex: 35,
    utilitiesIndex: 25,
    entertainmentIndex: 30,
    healthcareIndex: 25,
    safetyRating: 6,
    healthcareQuality: 7,
    climateRating: 7,
    englishProficiency: 4,
    internetSpeed: 55,
    workLifeBalance: 7,
    avgRent1Bed: 350,
    avgRent2Bed: 500,
    visaEase: 'easy',
    digitalNomadVisa: true,
    retirementVisa: true,
    incomeTaxRate: 35,
    capitalGainsTax: 15,
    nomadListUrl: 'https://nomadlist.com/buenos-aires',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Buenos%20Aires' },
    ],
    popularFor: ['Tango', 'Steak', 'Culture', 'Very Affordable'],
  },
  // Brazil
  {
    id: 'sao_paulo',
    name: 'São Paulo',
    country: 'Brazil',
    region: 'americas',
    flag: '🇧🇷',
    housingIndex: 55,
    transportIndex: 35,
    groceriesIndex: 50,
    utilitiesIndex: 40,
    entertainmentIndex: 45,
    healthcareIndex: 35,
    safetyRating: 5,
    healthcareQuality: 7,
    climateRating: 7,
    englishProficiency: 3,
    internetSpeed: 60,
    workLifeBalance: 6,
    avgRent1Bed: 550,
    avgRent2Bed: 800,
    visaEase: 'moderate',
    digitalNomadVisa: true,
    retirementVisa: true,
    incomeTaxRate: 27,
    capitalGainsTax: 15,
    nomadListUrl: 'https://nomadlist.com/sao-paulo',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Sao%20Paulo' },
    ],
    popularFor: ['Business', 'Finance', 'Culture', 'Food'],
  },
  {
    id: 'rio',
    name: 'Rio de Janeiro',
    country: 'Brazil',
    region: 'americas',
    flag: '🇧🇷',
    housingIndex: 50,
    transportIndex: 32,
    groceriesIndex: 48,
    utilitiesIndex: 38,
    entertainmentIndex: 42,
    healthcareIndex: 32,
    safetyRating: 4,
    healthcareQuality: 6,
    climateRating: 9,
    englishProficiency: 3,
    internetSpeed: 55,
    workLifeBalance: 8,
    avgRent1Bed: 500,
    avgRent2Bed: 750,
    visaEase: 'moderate',
    digitalNomadVisa: true,
    retirementVisa: true,
    incomeTaxRate: 27,
    capitalGainsTax: 15,
    nomadListUrl: 'https://nomadlist.com/rio-de-janeiro',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Rio%20de%20Janeiro' },
    ],
    popularFor: ['Beach', 'Carnival', 'Nature', 'Music'],
  },
];

// ============================================
// ASIA LOCATIONS
// ============================================
export const ASIA_LOCATIONS: Location[] = [
  // Thailand
  {
    id: 'bangkok',
    name: 'Bangkok',
    country: 'Thailand',
    region: 'asia',
    flag: '🇹🇭',
    housingIndex: 35,
    transportIndex: 25,
    groceriesIndex: 40,
    utilitiesIndex: 35,
    entertainmentIndex: 30,
    healthcareIndex: 25,
    safetyRating: 7,
    healthcareQuality: 8,
    climateRating: 6,
    englishProficiency: 4,
    internetSpeed: 70,
    workLifeBalance: 8,
    avgRent1Bed: 400,
    avgRent2Bed: 650,
    visaEase: 'moderate',
    digitalNomadVisa: true,
    retirementVisa: true,
    incomeTaxRate: 25,
    capitalGainsTax: 0,
    nomadListUrl: 'https://nomadlist.com/bangkok',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Bangkok' },
      { name: 'JobsDB', url: 'https://th.jobsdb.com' },
    ],
    popularFor: ['Digital Nomads', 'Food', 'Temples', 'Nightlife'],
  },
  {
    id: 'chiang_mai',
    name: 'Chiang Mai',
    country: 'Thailand',
    region: 'asia',
    flag: '🇹🇭',
    housingIndex: 28,
    transportIndex: 20,
    groceriesIndex: 35,
    utilitiesIndex: 30,
    entertainmentIndex: 25,
    healthcareIndex: 22,
    safetyRating: 8,
    healthcareQuality: 7,
    climateRating: 7,
    englishProficiency: 4,
    internetSpeed: 60,
    workLifeBalance: 9,
    avgRent1Bed: 300,
    avgRent2Bed: 450,
    visaEase: 'moderate',
    digitalNomadVisa: true,
    retirementVisa: true,
    incomeTaxRate: 25,
    capitalGainsTax: 0,
    nomadListUrl: 'https://nomadlist.com/chiang-mai',
    jobSearchUrls: [
      { name: 'Remote OK', url: 'https://remoteok.com' },
    ],
    popularFor: ['Digital Nomad Capital', 'Mountains', 'Temples', 'Yoga'],
  },
  {
    id: 'phuket',
    name: 'Phuket',
    country: 'Thailand',
    region: 'asia',
    flag: '🇹🇭',
    housingIndex: 40,
    transportIndex: 30,
    groceriesIndex: 45,
    utilitiesIndex: 38,
    entertainmentIndex: 40,
    healthcareIndex: 30,
    safetyRating: 7,
    healthcareQuality: 7,
    climateRating: 8,
    englishProficiency: 5,
    internetSpeed: 55,
    workLifeBalance: 9,
    avgRent1Bed: 450,
    avgRent2Bed: 700,
    visaEase: 'moderate',
    digitalNomadVisa: true,
    retirementVisa: true,
    incomeTaxRate: 25,
    capitalGainsTax: 0,
    nomadListUrl: 'https://nomadlist.com/phuket',
    jobSearchUrls: [
      { name: 'Remote OK', url: 'https://remoteok.com' },
    ],
    popularFor: ['Beach', 'Island Life', 'Diving', 'Retirement'],
  },
  // Indonesia
  {
    id: 'bali',
    name: 'Bali',
    country: 'Indonesia',
    region: 'asia',
    flag: '🇮🇩',
    housingIndex: 30,
    transportIndex: 20,
    groceriesIndex: 35,
    utilitiesIndex: 30,
    entertainmentIndex: 25,
    healthcareIndex: 20,
    safetyRating: 8,
    healthcareQuality: 6,
    climateRating: 8,
    englishProficiency: 5,
    internetSpeed: 35,
    workLifeBalance: 9,
    avgRent1Bed: 350,
    avgRent2Bed: 550,
    visaEase: 'moderate',
    digitalNomadVisa: true,
    retirementVisa: true,
    incomeTaxRate: 30,
    capitalGainsTax: 0,
    nomadListUrl: 'https://nomadlist.com/bali',
    jobSearchUrls: [
      { name: 'Remote OK', url: 'https://remoteok.com' },
      { name: 'We Work Remotely', url: 'https://weworkremotely.com' },
    ],
    popularFor: ['Digital Nomads', 'Surfing', 'Yoga', 'Rice Terraces'],
  },
  {
    id: 'jakarta',
    name: 'Jakarta',
    country: 'Indonesia',
    region: 'asia',
    flag: '🇮🇩',
    housingIndex: 40,
    transportIndex: 25,
    groceriesIndex: 40,
    utilitiesIndex: 35,
    entertainmentIndex: 35,
    healthcareIndex: 30,
    safetyRating: 6,
    healthcareQuality: 6,
    climateRating: 5,
    englishProficiency: 4,
    internetSpeed: 45,
    workLifeBalance: 6,
    avgRent1Bed: 450,
    avgRent2Bed: 700,
    visaEase: 'moderate',
    digitalNomadVisa: true,
    retirementVisa: true,
    incomeTaxRate: 30,
    capitalGainsTax: 0,
    nomadListUrl: 'https://nomadlist.com/jakarta',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Jakarta' },
    ],
    popularFor: ['Business', 'Startups', 'Shopping', 'Food'],
  },
  // Vietnam
  {
    id: 'ho_chi_minh',
    name: 'Ho Chi Minh City',
    country: 'Vietnam',
    region: 'asia',
    flag: '🇻🇳',
    housingIndex: 30,
    transportIndex: 20,
    groceriesIndex: 35,
    utilitiesIndex: 30,
    entertainmentIndex: 25,
    healthcareIndex: 22,
    safetyRating: 7,
    healthcareQuality: 6,
    climateRating: 6,
    englishProficiency: 4,
    internetSpeed: 55,
    workLifeBalance: 7,
    avgRent1Bed: 350,
    avgRent2Bed: 550,
    visaEase: 'moderate',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 35,
    capitalGainsTax: 0,
    nomadListUrl: 'https://nomadlist.com/ho-chi-minh-city',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Ho%20Chi%20Minh' },
    ],
    popularFor: ['Food', 'Affordable', 'Motorbikes', 'Startups'],
  },
  {
    id: 'hanoi',
    name: 'Hanoi',
    country: 'Vietnam',
    region: 'asia',
    flag: '🇻🇳',
    housingIndex: 28,
    transportIndex: 18,
    groceriesIndex: 32,
    utilitiesIndex: 28,
    entertainmentIndex: 22,
    healthcareIndex: 20,
    safetyRating: 8,
    healthcareQuality: 6,
    climateRating: 5,
    englishProficiency: 3,
    internetSpeed: 50,
    workLifeBalance: 7,
    avgRent1Bed: 320,
    avgRent2Bed: 500,
    visaEase: 'moderate',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 35,
    capitalGainsTax: 0,
    nomadListUrl: 'https://nomadlist.com/hanoi',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Hanoi' },
    ],
    popularFor: ['History', 'Food', 'Culture', 'Very Affordable'],
  },
  // Malaysia
  {
    id: 'kuala_lumpur',
    name: 'Kuala Lumpur',
    country: 'Malaysia',
    region: 'asia',
    flag: '🇲🇾',
    housingIndex: 40,
    transportIndex: 30,
    groceriesIndex: 45,
    utilitiesIndex: 35,
    entertainmentIndex: 35,
    healthcareIndex: 30,
    safetyRating: 7,
    healthcareQuality: 8,
    climateRating: 6,
    englishProficiency: 7,
    internetSpeed: 70,
    workLifeBalance: 7,
    avgRent1Bed: 450,
    avgRent2Bed: 700,
    visaEase: 'moderate',
    digitalNomadVisa: true,
    retirementVisa: true,
    incomeTaxRate: 28,
    capitalGainsTax: 0,
    nomadListUrl: 'https://nomadlist.com/kuala-lumpur',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Kuala%20Lumpur' },
    ],
    popularFor: ['Food', 'MM2H Program', 'Affordable', 'Diverse'],
  },
  // Singapore
  {
    id: 'singapore',
    name: 'Singapore',
    country: 'Singapore',
    region: 'asia',
    flag: '🇸🇬',
    housingIndex: 180,
    transportIndex: 85,
    groceriesIndex: 90,
    utilitiesIndex: 85,
    entertainmentIndex: 100,
    healthcareIndex: 120,
    safetyRating: 10,
    healthcareQuality: 10,
    climateRating: 5,
    englishProficiency: 9,
    internetSpeed: 200,
    workLifeBalance: 5,
    avgRent1Bed: 2000,
    avgRent2Bed: 3000,
    visaEase: 'moderate',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 22,
    capitalGainsTax: 0,
    nomadListUrl: 'https://nomadlist.com/singapore',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Singapore' },
      { name: 'JobStreet', url: 'https://www.jobstreet.com.sg' },
    ],
    popularFor: ['Finance', 'Tech', 'Safety', 'Food'],
  },
  // Japan
  {
    id: 'tokyo',
    name: 'Tokyo',
    country: 'Japan',
    region: 'asia',
    flag: '🇯🇵',
    housingIndex: 110,
    transportIndex: 85,
    groceriesIndex: 90,
    utilitiesIndex: 80,
    entertainmentIndex: 85,
    healthcareIndex: 90,
    safetyRating: 10,
    healthcareQuality: 10,
    climateRating: 7,
    englishProficiency: 4,
    internetSpeed: 130,
    workLifeBalance: 4,
    avgRent1Bed: 1200,
    avgRent2Bed: 1800,
    visaEase: 'difficult',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 45,
    capitalGainsTax: 20,
    nomadListUrl: 'https://nomadlist.com/tokyo',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Tokyo' },
      { name: 'GaijinPot', url: 'https://jobs.gaijinpot.com' },
    ],
    popularFor: ['Tech', 'Culture', 'Food', 'Safety'],
  },
  {
    id: 'osaka',
    name: 'Osaka',
    country: 'Japan',
    region: 'asia',
    flag: '🇯🇵',
    housingIndex: 85,
    transportIndex: 75,
    groceriesIndex: 85,
    utilitiesIndex: 75,
    entertainmentIndex: 75,
    healthcareIndex: 85,
    safetyRating: 10,
    healthcareQuality: 10,
    climateRating: 7,
    englishProficiency: 3,
    internetSpeed: 120,
    workLifeBalance: 5,
    avgRent1Bed: 900,
    avgRent2Bed: 1400,
    visaEase: 'difficult',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 45,
    capitalGainsTax: 20,
    nomadListUrl: 'https://nomadlist.com/osaka',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Osaka' },
    ],
    popularFor: ['Food', 'Culture', 'More Affordable', 'Friendly'],
  },
  // South Korea
  {
    id: 'seoul',
    name: 'Seoul',
    country: 'South Korea',
    region: 'asia',
    flag: '🇰🇷',
    housingIndex: 100,
    transportIndex: 60,
    groceriesIndex: 80,
    utilitiesIndex: 70,
    entertainmentIndex: 70,
    healthcareIndex: 75,
    safetyRating: 9,
    healthcareQuality: 9,
    climateRating: 6,
    englishProficiency: 5,
    internetSpeed: 200,
    workLifeBalance: 4,
    avgRent1Bed: 1000,
    avgRent2Bed: 1500,
    visaEase: 'moderate',
    digitalNomadVisa: true,
    retirementVisa: false,
    incomeTaxRate: 42,
    capitalGainsTax: 22,
    nomadListUrl: 'https://nomadlist.com/seoul',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Seoul' },
    ],
    popularFor: ['Tech', 'K-Pop', 'Food', 'Fast Internet'],
  },
  // Taiwan
  {
    id: 'taipei',
    name: 'Taipei',
    country: 'Taiwan',
    region: 'asia',
    flag: '🇹🇼',
    housingIndex: 70,
    transportIndex: 45,
    groceriesIndex: 60,
    utilitiesIndex: 55,
    entertainmentIndex: 50,
    healthcareIndex: 50,
    safetyRating: 9,
    healthcareQuality: 9,
    climateRating: 6,
    englishProficiency: 5,
    internetSpeed: 100,
    workLifeBalance: 6,
    avgRent1Bed: 700,
    avgRent2Bed: 1000,
    visaEase: 'moderate',
    digitalNomadVisa: true,
    retirementVisa: false,
    incomeTaxRate: 40,
    capitalGainsTax: 0,
    nomadListUrl: 'https://nomadlist.com/taipei',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Taipei' },
    ],
    popularFor: ['Tech', 'Food', 'Safety', 'Healthcare'],
  },
  // Philippines
  {
    id: 'manila',
    name: 'Manila',
    country: 'Philippines',
    region: 'asia',
    flag: '🇵🇭',
    housingIndex: 35,
    transportIndex: 20,
    groceriesIndex: 40,
    utilitiesIndex: 35,
    entertainmentIndex: 30,
    healthcareIndex: 25,
    safetyRating: 5,
    healthcareQuality: 6,
    climateRating: 6,
    englishProficiency: 8,
    internetSpeed: 40,
    workLifeBalance: 6,
    avgRent1Bed: 380,
    avgRent2Bed: 600,
    visaEase: 'easy',
    digitalNomadVisa: false,
    retirementVisa: true,
    incomeTaxRate: 32,
    capitalGainsTax: 6,
    nomadListUrl: 'https://nomadlist.com/manila',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Manila' },
    ],
    popularFor: ['English Speaking', 'BPO', 'Affordable', 'Beaches Nearby'],
  },
  // India
  {
    id: 'bangalore',
    name: 'Bangalore',
    country: 'India',
    region: 'asia',
    flag: '🇮🇳',
    housingIndex: 30,
    transportIndex: 18,
    groceriesIndex: 30,
    utilitiesIndex: 25,
    entertainmentIndex: 25,
    healthcareIndex: 20,
    safetyRating: 6,
    healthcareQuality: 7,
    climateRating: 8,
    englishProficiency: 7,
    internetSpeed: 50,
    workLifeBalance: 5,
    avgRent1Bed: 300,
    avgRent2Bed: 500,
    visaEase: 'moderate',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 30,
    capitalGainsTax: 20,
    nomadListUrl: 'https://nomadlist.com/bangalore',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Bangalore' },
      { name: 'Naukri', url: 'https://www.naukri.com' },
    ],
    popularFor: ['Tech Hub', 'Startups', 'IT', 'Climate'],
  },
];

// ============================================
// MIDDLE EAST & AFRICA LOCATIONS
// ============================================
export const MIDDLE_EAST_AFRICA_LOCATIONS: Location[] = [
  // UAE
  {
    id: 'dubai',
    name: 'Dubai',
    country: 'UAE',
    region: 'middle_east',
    flag: '🇦🇪',
    housingIndex: 140,
    transportIndex: 70,
    groceriesIndex: 85,
    utilitiesIndex: 75,
    entertainmentIndex: 100,
    healthcareIndex: 100,
    safetyRating: 9,
    healthcareQuality: 9,
    climateRating: 4,
    englishProficiency: 8,
    internetSpeed: 120,
    workLifeBalance: 5,
    avgRent1Bed: 1400,
    avgRent2Bed: 2200,
    visaEase: 'moderate',
    digitalNomadVisa: true,
    retirementVisa: true,
    incomeTaxRate: 0,
    capitalGainsTax: 0,
    nomadListUrl: 'https://nomadlist.com/dubai',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Dubai' },
      { name: 'Bayt', url: 'https://www.bayt.com/en/uae/jobs/in/dubai/' },
    ],
    popularFor: ['Tax Free', 'Finance', 'Luxury', 'Expats'],
  },
  {
    id: 'abu_dhabi',
    name: 'Abu Dhabi',
    country: 'UAE',
    region: 'middle_east',
    flag: '🇦🇪',
    housingIndex: 120,
    transportIndex: 65,
    groceriesIndex: 82,
    utilitiesIndex: 70,
    entertainmentIndex: 90,
    healthcareIndex: 95,
    safetyRating: 9,
    healthcareQuality: 9,
    climateRating: 4,
    englishProficiency: 8,
    internetSpeed: 110,
    workLifeBalance: 6,
    avgRent1Bed: 1200,
    avgRent2Bed: 1800,
    visaEase: 'moderate',
    digitalNomadVisa: true,
    retirementVisa: true,
    incomeTaxRate: 0,
    capitalGainsTax: 0,
    nomadListUrl: 'https://nomadlist.com/abu-dhabi',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Abu%20Dhabi' },
    ],
    popularFor: ['Oil & Gas', 'Government', 'Family', 'Tax Free'],
  },
  // Israel
  {
    id: 'tel_aviv',
    name: 'Tel Aviv',
    country: 'Israel',
    region: 'middle_east',
    flag: '🇮🇱',
    housingIndex: 150,
    transportIndex: 80,
    groceriesIndex: 95,
    utilitiesIndex: 85,
    entertainmentIndex: 95,
    healthcareIndex: 90,
    safetyRating: 6,
    healthcareQuality: 9,
    climateRating: 8,
    englishProficiency: 8,
    internetSpeed: 100,
    workLifeBalance: 6,
    avgRent1Bed: 1500,
    avgRent2Bed: 2200,
    visaEase: 'moderate',
    digitalNomadVisa: true,
    retirementVisa: false,
    incomeTaxRate: 47,
    capitalGainsTax: 25,
    nomadListUrl: 'https://nomadlist.com/tel-aviv',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Tel%20Aviv' },
    ],
    popularFor: ['Startups', 'Tech', 'Beach', 'Nightlife'],
  },
  // South Africa
  {
    id: 'cape_town',
    name: 'Cape Town',
    country: 'South Africa',
    region: 'africa',
    flag: '🇿🇦',
    housingIndex: 45,
    transportIndex: 35,
    groceriesIndex: 45,
    utilitiesIndex: 40,
    entertainmentIndex: 40,
    healthcareIndex: 35,
    safetyRating: 4,
    healthcareQuality: 7,
    climateRating: 9,
    englishProficiency: 9,
    internetSpeed: 40,
    workLifeBalance: 8,
    avgRent1Bed: 500,
    avgRent2Bed: 750,
    visaEase: 'moderate',
    digitalNomadVisa: false,
    retirementVisa: true,
    incomeTaxRate: 45,
    capitalGainsTax: 18,
    nomadListUrl: 'https://nomadlist.com/cape-town',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Cape%20Town' },
    ],
    popularFor: ['Nature', 'Wine', 'Digital Nomads', 'Weather'],
  },
  // Morocco
  {
    id: 'marrakech',
    name: 'Marrakech',
    country: 'Morocco',
    region: 'africa',
    flag: '🇲🇦',
    housingIndex: 35,
    transportIndex: 25,
    groceriesIndex: 40,
    utilitiesIndex: 35,
    entertainmentIndex: 30,
    healthcareIndex: 30,
    safetyRating: 7,
    healthcareQuality: 5,
    climateRating: 8,
    englishProficiency: 4,
    internetSpeed: 30,
    workLifeBalance: 7,
    avgRent1Bed: 350,
    avgRent2Bed: 550,
    visaEase: 'easy',
    digitalNomadVisa: false,
    retirementVisa: false,
    incomeTaxRate: 38,
    capitalGainsTax: 20,
    nomadListUrl: 'https://nomadlist.com/marrakech',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Marrakech' },
    ],
    popularFor: ['Culture', 'Affordable', 'Riads', 'Food'],
  },
];

// ============================================
// OCEANIA LOCATIONS
// ============================================
export const OCEANIA_LOCATIONS: Location[] = [
  // Australia
  {
    id: 'sydney',
    name: 'Sydney',
    country: 'Australia',
    region: 'oceania',
    flag: '🇦🇺',
    housingIndex: 160,
    transportIndex: 95,
    groceriesIndex: 95,
    utilitiesIndex: 90,
    entertainmentIndex: 105,
    healthcareIndex: 100,
    safetyRating: 8,
    healthcareQuality: 9,
    climateRating: 9,
    englishProficiency: 10,
    internetSpeed: 80,
    workLifeBalance: 8,
    avgRent1Bed: 1800,
    avgRent2Bed: 2500,
    visaEase: 'moderate',
    digitalNomadVisa: false,
    retirementVisa: true,
    incomeTaxRate: 45,
    capitalGainsTax: 23,
    nomadListUrl: 'https://nomadlist.com/sydney',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Sydney' },
      { name: 'Seek', url: 'https://www.seek.com.au/jobs/in-sydney' },
    ],
    popularFor: ['Beach', 'Quality of Life', 'Finance', 'Outdoors'],
  },
  {
    id: 'melbourne',
    name: 'Melbourne',
    country: 'Australia',
    region: 'oceania',
    flag: '🇦🇺',
    housingIndex: 140,
    transportIndex: 90,
    groceriesIndex: 90,
    utilitiesIndex: 88,
    entertainmentIndex: 100,
    healthcareIndex: 100,
    safetyRating: 8,
    healthcareQuality: 9,
    climateRating: 7,
    englishProficiency: 10,
    internetSpeed: 75,
    workLifeBalance: 8,
    avgRent1Bed: 1500,
    avgRent2Bed: 2100,
    visaEase: 'moderate',
    digitalNomadVisa: false,
    retirementVisa: true,
    incomeTaxRate: 45,
    capitalGainsTax: 23,
    nomadListUrl: 'https://nomadlist.com/melbourne',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Melbourne' },
      { name: 'Seek', url: 'https://www.seek.com.au/jobs/in-melbourne' },
    ],
    popularFor: ['Coffee', 'Arts', 'Sports', 'Liveable'],
  },
  // New Zealand
  {
    id: 'auckland',
    name: 'Auckland',
    country: 'New Zealand',
    region: 'oceania',
    flag: '🇳🇿',
    housingIndex: 130,
    transportIndex: 85,
    groceriesIndex: 90,
    utilitiesIndex: 85,
    entertainmentIndex: 90,
    healthcareIndex: 95,
    safetyRating: 9,
    healthcareQuality: 9,
    climateRating: 7,
    englishProficiency: 10,
    internetSpeed: 70,
    workLifeBalance: 9,
    avgRent1Bed: 1300,
    avgRent2Bed: 1800,
    visaEase: 'moderate',
    digitalNomadVisa: false,
    retirementVisa: true,
    incomeTaxRate: 39,
    capitalGainsTax: 0,
    nomadListUrl: 'https://nomadlist.com/auckland',
    jobSearchUrls: [
      { name: 'LinkedIn', url: 'https://www.linkedin.com/jobs/search/?location=Auckland' },
      { name: 'Seek NZ', url: 'https://www.seek.co.nz/jobs/in-auckland' },
    ],
    popularFor: ['Nature', 'Work-Life Balance', 'Sailing', 'Quality of Life'],
  },
];

// ============================================
// COMBINE ALL LOCATIONS
// ============================================
export const ALL_LOCATIONS: Location[] = [
  ...UK_LOCATIONS,
  ...EUROPE_LOCATIONS,
  ...AMERICAS_LOCATIONS,
  ...ASIA_LOCATIONS,
  ...MIDDLE_EAST_AFRICA_LOCATIONS,
  ...OCEANIA_LOCATIONS,
];

// Helper function to search locations
export function searchLocations(query: string, region?: LocationType): Location[] {
  const normalizedQuery = query.toLowerCase().trim();

  return ALL_LOCATIONS.filter(loc => {
    const matchesRegion = !region || loc.region === region;
    const matchesQuery = !normalizedQuery ||
      loc.name.toLowerCase().includes(normalizedQuery) ||
      loc.country.toLowerCase().includes(normalizedQuery) ||
      loc.popularFor.some(tag => tag.toLowerCase().includes(normalizedQuery));

    return matchesRegion && matchesQuery;
  });
}

// Get locations grouped by region
export function getLocationsByRegion(): Record<LocationType, Location[]> {
  return {
    uk: UK_LOCATIONS,
    europe: EUROPE_LOCATIONS,
    americas: AMERICAS_LOCATIONS,
    asia: ASIA_LOCATIONS,
    middle_east: MIDDLE_EAST_AFRICA_LOCATIONS.filter(l => l.region === 'middle_east'),
    oceania: OCEANIA_LOCATIONS,
    africa: MIDDLE_EAST_AFRICA_LOCATIONS.filter(l => l.region === 'africa'),
  };
}
