import type { Product } from '@/types/calculator';

export const UK_PRODUCTS: Product[] = [
  // Food & Drink
  { name: 'Pret Coffee', price: 3.50, emoji: '☕', category: 'food' },
  { name: 'Meal Deal', price: 3.99, emoji: '🥪', category: 'food' },
  { name: 'Greggs Sausage Roll', price: 1.35, emoji: '🥐', category: 'food' },
  { name: "Nando's for Two", price: 45, emoji: '🍗', category: 'food' },
  { name: "Domino's Pizza", price: 18.99, emoji: '🍕', category: 'food' },
  { name: 'Weekly Food Shop', price: 85, emoji: '🛒', category: 'food' },
  { name: 'Deliveroo Order', price: 25, emoji: '🛵', category: 'food' },
  { name: 'Pint at the Pub', price: 6.50, emoji: '🍺', category: 'food' },
  { name: 'Costa Latte', price: 4.15, emoji: '☕', category: 'food' },
  { name: 'Freddo', price: 0.35, emoji: '🐸', category: 'food' },
  { name: 'Bottle of Wine (Tesco)', price: 7, emoji: '🍷', category: 'food' },
  { name: 'Sunday Roast', price: 18, emoji: '🍖', category: 'food' },

  // Tech
  { name: 'iPhone 15 Pro', price: 1199, emoji: '📱', category: 'tech' },
  { name: 'MacBook Air M3', price: 1099, emoji: '💻', category: 'tech' },
  { name: 'AirPods Pro', price: 229, emoji: '🎧', category: 'tech' },
  { name: 'PS5', price: 479, emoji: '🎮', category: 'tech' },
  { name: 'Nintendo Switch OLED', price: 309, emoji: '🕹️', category: 'tech' },
  { name: 'iPad 10th Gen', price: 499, emoji: '📱', category: 'tech' },
  { name: 'Apple Watch SE', price: 219, emoji: '⌚', category: 'tech' },
  { name: 'Samsung Galaxy S24', price: 799, emoji: '📱', category: 'tech' },
  { name: 'Kindle Paperwhite', price: 149, emoji: '📚', category: 'tech' },
  { name: 'JBL Bluetooth Speaker', price: 89, emoji: '🔊', category: 'tech' },

  // Subscriptions (Monthly)
  { name: 'Netflix (Standard)', price: 10.99, emoji: '📺', category: 'subscriptions', period: 'month' },
  { name: 'Spotify Premium', price: 11.99, emoji: '🎵', category: 'subscriptions', period: 'month' },
  { name: 'Disney+', price: 7.99, emoji: '🏰', category: 'subscriptions', period: 'month' },
  { name: 'Amazon Prime', price: 8.99, emoji: '📦', category: 'subscriptions', period: 'month' },
  { name: 'YouTube Premium', price: 12.99, emoji: '▶️', category: 'subscriptions', period: 'month' },
  { name: 'Apple Music', price: 10.99, emoji: '🍎', category: 'subscriptions', period: 'month' },
  { name: 'Sky Sports', price: 34, emoji: '⚽', category: 'subscriptions', period: 'month' },
  { name: 'PureGym', price: 24.99, emoji: '💪', category: 'subscriptions', period: 'month' },
  { name: 'David Lloyd', price: 120, emoji: '🏊', category: 'subscriptions', period: 'month' },
  { name: 'NOW TV Entertainment', price: 9.99, emoji: '📺', category: 'subscriptions', period: 'month' },
  { name: 'Xbox Game Pass', price: 12.99, emoji: '🎮', category: 'subscriptions', period: 'month' },
  { name: 'PlayStation Plus', price: 10.99, emoji: '🎮', category: 'subscriptions', period: 'month' },
  { name: 'iCloud 200GB', price: 2.99, emoji: '☁️', category: 'subscriptions', period: 'month' },
  { name: 'Audible', price: 7.99, emoji: '🎧', category: 'subscriptions', period: 'month' },

  // Subscriptions (Annual)
  { name: 'Amazon Prime (Year)', price: 95, emoji: '📦', category: 'subscriptions', period: 'year' },
  { name: 'Costco Membership', price: 33.60, emoji: '🏪', category: 'subscriptions', period: 'year' },
  { name: 'AA Breakdown Cover', price: 149, emoji: '🚗', category: 'subscriptions', period: 'year' },
  { name: 'RAC Breakdown', price: 99, emoji: '🚙', category: 'subscriptions', period: 'year' },

  // Transport
  { name: 'London Zone 1-2 Travelcard (Month)', price: 164.20, emoji: '🚇', category: 'transport' },
  { name: 'London Zone 1-6 Travelcard (Month)', price: 282.60, emoji: '🚇', category: 'transport' },
  { name: 'Single Bus Fare (London)', price: 1.75, emoji: '🚌', category: 'transport' },
  { name: 'Tank of Petrol', price: 85, emoji: '⛽', category: 'transport' },
  { name: 'MOT Test', price: 54.85, emoji: '🔧', category: 'transport' },
  { name: 'Car Service (Basic)', price: 150, emoji: '🚗', category: 'transport' },
  { name: 'New Tyres (x4)', price: 400, emoji: '🛞', category: 'transport' },
  { name: 'Car Insurance (Year, Avg)', price: 924, emoji: '📋', category: 'transport' },
  { name: 'Road Tax (Avg)', price: 180, emoji: '📜', category: 'transport' },
  { name: 'Train to Manchester (Peak)', price: 95, emoji: '🚆', category: 'transport' },
  { name: 'Uber (5 mile)', price: 15, emoji: '🚕', category: 'transport' },
  { name: 'Santander Bike (Day)', price: 3, emoji: '🚲', category: 'transport' },

  // Home
  { name: 'Average Monthly Rent (UK)', price: 1279, emoji: '🏠', category: 'home' },
  { name: 'London Monthly Rent (1 bed)', price: 1850, emoji: '🏙️', category: 'home' },
  { name: 'Council Tax Band D (Month)', price: 175, emoji: '🏛️', category: 'home' },
  { name: 'Energy Bill (Month, Avg)', price: 135, emoji: '⚡', category: 'home' },
  { name: 'Broadband (Avg)', price: 35, emoji: '📡', category: 'home' },
  { name: 'TV Licence', price: 169.50, emoji: '📺', category: 'home', period: 'year' },
  { name: 'Contents Insurance (Year)', price: 120, emoji: '🛋️', category: 'home' },
  { name: 'Dyson V15', price: 699, emoji: '🧹', category: 'home' },
  { name: 'IKEA Billy Bookcase', price: 55, emoji: '📚', category: 'home' },
  { name: 'Washing Machine', price: 350, emoji: '🧺', category: 'home' },
  { name: 'New Sofa', price: 800, emoji: '🛋️', category: 'home' },
  { name: 'King Size Bed', price: 600, emoji: '🛏️', category: 'home' },

  // Lifestyle
  { name: 'Haircut (Barber)', price: 18, emoji: '💇', category: 'lifestyle' },
  { name: 'Haircut (Salon)', price: 55, emoji: '💇‍♀️', category: 'lifestyle' },
  { name: 'Cinema Ticket', price: 14, emoji: '🎬', category: 'lifestyle' },
  { name: 'Concert Ticket (Avg)', price: 75, emoji: '🎤', category: 'lifestyle' },
  { name: 'Premier League Ticket', price: 55, emoji: '⚽', category: 'lifestyle' },
  { name: 'Gym Trainers (Nike)', price: 120, emoji: '👟', category: 'lifestyle' },
  { name: 'Zara Jeans', price: 35.99, emoji: '👖', category: 'lifestyle' },
  { name: 'North Face Jacket', price: 200, emoji: '🧥', category: 'lifestyle' },
  { name: 'Weekend in Paris (Budget)', price: 350, emoji: '✈️', category: 'lifestyle' },
  { name: 'UK Holiday (Week)', price: 800, emoji: '🏖️', category: 'lifestyle' },
  { name: 'Christmas Gifts (Avg)', price: 250, emoji: '🎄', category: 'lifestyle' },
  { name: 'Wedding Guest Outfit', price: 180, emoji: '👗', category: 'lifestyle' },
  { name: 'Night Out (London)', price: 100, emoji: '🍸', category: 'lifestyle' },
  { name: 'Tattoo (Small)', price: 80, emoji: '💉', category: 'lifestyle' },
  { name: 'Books (Month)', price: 25, emoji: '📖', category: 'lifestyle' },
];
